// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xchenidct_f2r_vectorbody_s2e_forend212.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XChenidct_f2r_vectorbody_s2e_forend212_CfgInitialize(XChenidct_f2r_vectorbody_s2e_forend212 *InstancePtr, XChenidct_f2r_vectorbody_s2e_forend212_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Bus_ctrl_BaseAddress = ConfigPtr->Bus_ctrl_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XChenidct_f2r_vectorbody_s2e_forend212_Start(XChenidct_f2r_vectorbody_s2e_forend212 *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XChenidct_f2r_vectorbody_s2e_forend212_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XCHENIDCT_F2R_VECTORBODY_S2E_FOREND212_BUS_CTRL_ADDR_AP_CTRL) & 0x80;
    XChenidct_f2r_vectorbody_s2e_forend212_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XCHENIDCT_F2R_VECTORBODY_S2E_FOREND212_BUS_CTRL_ADDR_AP_CTRL, Data | 0x01);
}

u32 XChenidct_f2r_vectorbody_s2e_forend212_IsDone(XChenidct_f2r_vectorbody_s2e_forend212 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XChenidct_f2r_vectorbody_s2e_forend212_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XCHENIDCT_F2R_VECTORBODY_S2E_FOREND212_BUS_CTRL_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XChenidct_f2r_vectorbody_s2e_forend212_IsIdle(XChenidct_f2r_vectorbody_s2e_forend212 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XChenidct_f2r_vectorbody_s2e_forend212_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XCHENIDCT_F2R_VECTORBODY_S2E_FOREND212_BUS_CTRL_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XChenidct_f2r_vectorbody_s2e_forend212_IsReady(XChenidct_f2r_vectorbody_s2e_forend212 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XChenidct_f2r_vectorbody_s2e_forend212_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XCHENIDCT_F2R_VECTORBODY_S2E_FOREND212_BUS_CTRL_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XChenidct_f2r_vectorbody_s2e_forend212_EnableAutoRestart(XChenidct_f2r_vectorbody_s2e_forend212 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XChenidct_f2r_vectorbody_s2e_forend212_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XCHENIDCT_F2R_VECTORBODY_S2E_FOREND212_BUS_CTRL_ADDR_AP_CTRL, 0x80);
}

void XChenidct_f2r_vectorbody_s2e_forend212_DisableAutoRestart(XChenidct_f2r_vectorbody_s2e_forend212 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XChenidct_f2r_vectorbody_s2e_forend212_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XCHENIDCT_F2R_VECTORBODY_S2E_FOREND212_BUS_CTRL_ADDR_AP_CTRL, 0);
}

void XChenidct_f2r_vectorbody_s2e_forend212_Set_y(XChenidct_f2r_vectorbody_s2e_forend212 *InstancePtr, u64 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XChenidct_f2r_vectorbody_s2e_forend212_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XCHENIDCT_F2R_VECTORBODY_S2E_FOREND212_BUS_CTRL_ADDR_Y_DATA, (u32)(Data));
    XChenidct_f2r_vectorbody_s2e_forend212_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XCHENIDCT_F2R_VECTORBODY_S2E_FOREND212_BUS_CTRL_ADDR_Y_DATA + 4, (u32)(Data >> 32));
}

u64 XChenidct_f2r_vectorbody_s2e_forend212_Get_y(XChenidct_f2r_vectorbody_s2e_forend212 *InstancePtr) {
    u64 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XChenidct_f2r_vectorbody_s2e_forend212_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XCHENIDCT_F2R_VECTORBODY_S2E_FOREND212_BUS_CTRL_ADDR_Y_DATA);
    Data += (u64)XChenidct_f2r_vectorbody_s2e_forend212_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XCHENIDCT_F2R_VECTORBODY_S2E_FOREND212_BUS_CTRL_ADDR_Y_DATA + 4) << 32;
    return Data;
}

void XChenidct_f2r_vectorbody_s2e_forend212_InterruptGlobalEnable(XChenidct_f2r_vectorbody_s2e_forend212 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XChenidct_f2r_vectorbody_s2e_forend212_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XCHENIDCT_F2R_VECTORBODY_S2E_FOREND212_BUS_CTRL_ADDR_GIE, 1);
}

void XChenidct_f2r_vectorbody_s2e_forend212_InterruptGlobalDisable(XChenidct_f2r_vectorbody_s2e_forend212 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XChenidct_f2r_vectorbody_s2e_forend212_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XCHENIDCT_F2R_VECTORBODY_S2E_FOREND212_BUS_CTRL_ADDR_GIE, 0);
}

void XChenidct_f2r_vectorbody_s2e_forend212_InterruptEnable(XChenidct_f2r_vectorbody_s2e_forend212 *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XChenidct_f2r_vectorbody_s2e_forend212_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XCHENIDCT_F2R_VECTORBODY_S2E_FOREND212_BUS_CTRL_ADDR_IER);
    XChenidct_f2r_vectorbody_s2e_forend212_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XCHENIDCT_F2R_VECTORBODY_S2E_FOREND212_BUS_CTRL_ADDR_IER, Register | Mask);
}

void XChenidct_f2r_vectorbody_s2e_forend212_InterruptDisable(XChenidct_f2r_vectorbody_s2e_forend212 *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XChenidct_f2r_vectorbody_s2e_forend212_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XCHENIDCT_F2R_VECTORBODY_S2E_FOREND212_BUS_CTRL_ADDR_IER);
    XChenidct_f2r_vectorbody_s2e_forend212_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XCHENIDCT_F2R_VECTORBODY_S2E_FOREND212_BUS_CTRL_ADDR_IER, Register & (~Mask));
}

void XChenidct_f2r_vectorbody_s2e_forend212_InterruptClear(XChenidct_f2r_vectorbody_s2e_forend212 *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XChenidct_f2r_vectorbody_s2e_forend212_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XCHENIDCT_F2R_VECTORBODY_S2E_FOREND212_BUS_CTRL_ADDR_ISR, Mask);
}

u32 XChenidct_f2r_vectorbody_s2e_forend212_InterruptGetEnabled(XChenidct_f2r_vectorbody_s2e_forend212 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XChenidct_f2r_vectorbody_s2e_forend212_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XCHENIDCT_F2R_VECTORBODY_S2E_FOREND212_BUS_CTRL_ADDR_IER);
}

u32 XChenidct_f2r_vectorbody_s2e_forend212_InterruptGetStatus(XChenidct_f2r_vectorbody_s2e_forend212 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XChenidct_f2r_vectorbody_s2e_forend212_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XCHENIDCT_F2R_VECTORBODY_S2E_FOREND212_BUS_CTRL_ADDR_ISR);
}

