# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2017.4
# Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
# 
# ==============================================================


/home/tools/Xilinx/Vivado/2017.4/bin/vivado  -notrace -mode batch -source ipi_example.tcl -tclargs xczu9eg-ffvb1156-2-i ../xilinx_com_hls_WriteOneBlock_f2r_entry_s2e_forEnd13_1_0.zip
