// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XDECODE_START_F2R_VECTORPH_S2E_FORBODY96PREHEADER_H
#define XDECODE_START_F2R_VECTORPH_S2E_FORBODY96PREHEADER_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xdecode_start_f2r_vectorph_s2e_forbody96preheader_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Bus_ctrl_BaseAddress;
} XDecode_start_f2r_vectorph_s2e_forbody96preheader_Config;
#endif

typedef struct {
    u32 Bus_ctrl_BaseAddress;
    u32 IsReady;
} XDecode_start_f2r_vectorph_s2e_forbody96preheader;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XDecode_start_f2r_vectorph_s2e_forbody96preheader_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XDecode_start_f2r_vectorph_s2e_forbody96preheader_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XDecode_start_f2r_vectorph_s2e_forbody96preheader_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XDecode_start_f2r_vectorph_s2e_forbody96preheader_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XDecode_start_f2r_vectorph_s2e_forbody96preheader_Initialize(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr, u16 DeviceId);
XDecode_start_f2r_vectorph_s2e_forbody96preheader_Config* XDecode_start_f2r_vectorph_s2e_forbody96preheader_LookupConfig(u16 DeviceId);
int XDecode_start_f2r_vectorph_s2e_forbody96preheader_CfgInitialize(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr, XDecode_start_f2r_vectorph_s2e_forbody96preheader_Config *ConfigPtr);
#else
int XDecode_start_f2r_vectorph_s2e_forbody96preheader_Initialize(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr, const char* InstanceName);
int XDecode_start_f2r_vectorph_s2e_forbody96preheader_Release(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr);
#endif

void XDecode_start_f2r_vectorph_s2e_forbody96preheader_Start(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr);
u32 XDecode_start_f2r_vectorph_s2e_forbody96preheader_IsDone(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr);
u32 XDecode_start_f2r_vectorph_s2e_forbody96preheader_IsIdle(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr);
u32 XDecode_start_f2r_vectorph_s2e_forbody96preheader_IsReady(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr);
void XDecode_start_f2r_vectorph_s2e_forbody96preheader_EnableAutoRestart(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr);
void XDecode_start_f2r_vectorph_s2e_forbody96preheader_DisableAutoRestart(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr);

void XDecode_start_f2r_vectorph_s2e_forbody96preheader_Set_y_buf(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr, u64 Data);
u64 XDecode_start_f2r_vectorph_s2e_forbody96preheader_Get_y_buf(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr);
void XDecode_start_f2r_vectorph_s2e_forbody96preheader_Set_u_buf(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr, u64 Data);
u64 XDecode_start_f2r_vectorph_s2e_forbody96preheader_Get_u_buf(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr);
void XDecode_start_f2r_vectorph_s2e_forbody96preheader_Set_v_buf(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr, u64 Data);
u64 XDecode_start_f2r_vectorph_s2e_forbody96preheader_Get_v_buf(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr);
void XDecode_start_f2r_vectorph_s2e_forbody96preheader_Set_rgb_buf(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr, u64 Data);
u64 XDecode_start_f2r_vectorph_s2e_forbody96preheader_Get_rgb_buf(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr);

void XDecode_start_f2r_vectorph_s2e_forbody96preheader_InterruptGlobalEnable(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr);
void XDecode_start_f2r_vectorph_s2e_forbody96preheader_InterruptGlobalDisable(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr);
void XDecode_start_f2r_vectorph_s2e_forbody96preheader_InterruptEnable(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr, u32 Mask);
void XDecode_start_f2r_vectorph_s2e_forbody96preheader_InterruptDisable(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr, u32 Mask);
void XDecode_start_f2r_vectorph_s2e_forbody96preheader_InterruptClear(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr, u32 Mask);
u32 XDecode_start_f2r_vectorph_s2e_forbody96preheader_InterruptGetEnabled(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr);
u32 XDecode_start_f2r_vectorph_s2e_forbody96preheader_InterruptGetStatus(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
