// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xdecode_start_f2r_vectorph_s2e_forbody96preheader.h"

extern XDecode_start_f2r_vectorph_s2e_forbody96preheader_Config XDecode_start_f2r_vectorph_s2e_forbody96preheader_ConfigTable[];

XDecode_start_f2r_vectorph_s2e_forbody96preheader_Config *XDecode_start_f2r_vectorph_s2e_forbody96preheader_LookupConfig(u16 DeviceId) {
	XDecode_start_f2r_vectorph_s2e_forbody96preheader_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XDECODE_START_F2R_VECTORPH_S2E_FORBODY96PREHEADER_NUM_INSTANCES; Index++) {
		if (XDecode_start_f2r_vectorph_s2e_forbody96preheader_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XDecode_start_f2r_vectorph_s2e_forbody96preheader_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XDecode_start_f2r_vectorph_s2e_forbody96preheader_Initialize(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr, u16 DeviceId) {
	XDecode_start_f2r_vectorph_s2e_forbody96preheader_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XDecode_start_f2r_vectorph_s2e_forbody96preheader_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XDecode_start_f2r_vectorph_s2e_forbody96preheader_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

