// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern void AESL_WRAP_WriteOneBlock_f2r_entry_s2e_forEnd13 (
int store[64],
unsigned char out_buf[5310],
int width,
int height,
int voffs,
int hoffs);
