// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "Loop_0_proc19.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic Loop_0_proc19::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic Loop_0_proc19::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> Loop_0_proc19::ap_ST_fsm_state1 = "1";
const sc_lv<3> Loop_0_proc19::ap_ST_fsm_state2 = "10";
const sc_lv<3> Loop_0_proc19::ap_ST_fsm_state3 = "100";
const sc_lv<32> Loop_0_proc19::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> Loop_0_proc19::ap_const_lv32_1 = "1";
const sc_lv<1> Loop_0_proc19::ap_const_lv1_0 = "0";
const sc_lv<6> Loop_0_proc19::ap_const_lv6_0 = "000000";
const sc_lv<32> Loop_0_proc19::ap_const_lv32_2 = "10";
const sc_lv<5> Loop_0_proc19::ap_const_lv5_0 = "00000";
const sc_lv<6> Loop_0_proc19::ap_const_lv6_20 = "100000";
const sc_lv<32> Loop_0_proc19::ap_const_lv32_4 = "100";
const sc_lv<32> Loop_0_proc19::ap_const_lv32_5 = "101";
const sc_lv<5> Loop_0_proc19::ap_const_lv5_1 = "1";
const sc_lv<5> Loop_0_proc19::ap_const_lv5_2 = "10";
const sc_lv<5> Loop_0_proc19::ap_const_lv5_3 = "11";
const sc_lv<5> Loop_0_proc19::ap_const_lv5_4 = "100";
const sc_lv<5> Loop_0_proc19::ap_const_lv5_5 = "101";
const sc_lv<5> Loop_0_proc19::ap_const_lv5_6 = "110";
const sc_lv<5> Loop_0_proc19::ap_const_lv5_7 = "111";
const sc_lv<5> Loop_0_proc19::ap_const_lv5_8 = "1000";
const sc_lv<5> Loop_0_proc19::ap_const_lv5_9 = "1001";
const sc_lv<5> Loop_0_proc19::ap_const_lv5_A = "1010";
const sc_lv<5> Loop_0_proc19::ap_const_lv5_B = "1011";
const sc_lv<5> Loop_0_proc19::ap_const_lv5_C = "1100";
const sc_lv<5> Loop_0_proc19::ap_const_lv5_D = "1101";
const sc_lv<5> Loop_0_proc19::ap_const_lv5_E = "1110";
const sc_lv<5> Loop_0_proc19::ap_const_lv5_F = "1111";
const sc_lv<6> Loop_0_proc19::ap_const_lv6_10 = "10000";
const sc_lv<1> Loop_0_proc19::ap_const_lv1_1 = "1";
const bool Loop_0_proc19::ap_const_boolean_1 = true;

Loop_0_proc19::Loop_0_proc19(sc_module_name name) : sc_module(name), mVcdFile(0) {
    zigzag_index_U = new Loop_0_proc19_zigbkb("zigzag_index_U");
    zigzag_index_U->clk(ap_clk);
    zigzag_index_U->reset(ap_rst);
    zigzag_index_U->address0(zigzag_index_address0);
    zigzag_index_U->ce0(zigzag_index_ce0);
    zigzag_index_U->q0(zigzag_index_q0);
    zigzag_index_U->address1(zigzag_index_address1);
    zigzag_index_U->ce1(zigzag_index_ce1);
    zigzag_index_U->q1(zigzag_index_q1);
    zigzag_index_U->address2(zigzag_index_address2);
    zigzag_index_U->ce2(zigzag_index_ce2);
    zigzag_index_U->q2(zigzag_index_q2);
    zigzag_index_U->address3(zigzag_index_address3);
    zigzag_index_U->ce3(zigzag_index_ce3);
    zigzag_index_U->q3(zigzag_index_q3);
    zigzag_index_U->address4(zigzag_index_address4);
    zigzag_index_U->ce4(zigzag_index_ce4);
    zigzag_index_U->q4(zigzag_index_q4);
    zigzag_index_U->address5(zigzag_index_address5);
    zigzag_index_U->ce5(zigzag_index_ce5);
    zigzag_index_U->q5(zigzag_index_q5);
    zigzag_index_U->address6(zigzag_index_address6);
    zigzag_index_U->ce6(zigzag_index_ce6);
    zigzag_index_U->q6(zigzag_index_q6);
    zigzag_index_U->address7(zigzag_index_address7);
    zigzag_index_U->ce7(zigzag_index_ce7);
    zigzag_index_U->q7(zigzag_index_q7);
    zigzag_index_U->address8(zigzag_index_address8);
    zigzag_index_U->ce8(zigzag_index_ce8);
    zigzag_index_U->q8(zigzag_index_q8);
    zigzag_index_U->address9(zigzag_index_address9);
    zigzag_index_U->ce9(zigzag_index_ce9);
    zigzag_index_U->q9(zigzag_index_q9);
    zigzag_index_U->address10(zigzag_index_address10);
    zigzag_index_U->ce10(zigzag_index_ce10);
    zigzag_index_U->q10(zigzag_index_q10);
    zigzag_index_U->address11(zigzag_index_address11);
    zigzag_index_U->ce11(zigzag_index_ce11);
    zigzag_index_U->q11(zigzag_index_q11);
    zigzag_index_U->address12(zigzag_index_address12);
    zigzag_index_U->ce12(zigzag_index_ce12);
    zigzag_index_U->q12(zigzag_index_q12);
    zigzag_index_U->address13(zigzag_index_address13);
    zigzag_index_U->ce13(zigzag_index_ce13);
    zigzag_index_U->q13(zigzag_index_q13);
    zigzag_index_U->address14(zigzag_index_address14);
    zigzag_index_U->ce14(zigzag_index_ce14);
    zigzag_index_U->q14(zigzag_index_q14);
    zigzag_index_U->address15(zigzag_index_address15);
    zigzag_index_U->ce15(zigzag_index_ce15);
    zigzag_index_U->q15(zigzag_index_q15);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( i_0_i_i_c_full_n );
    sensitive << ( imatrix_offset_out_full_n );
    sensitive << ( omatrix_offset_out_full_n );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_i_i_i_i_i_s_fu_602_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_i_i_i_i_i_s_fu_602_p2 );

    SC_METHOD(thread_exitcond1_i_i_i_i_i_s_fu_602_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( j_0_i_i_i_i_i_i_i_reg_578 );

    SC_METHOD(thread_i_0_i_i_c_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( i_0_i_i_c_full_n );

    SC_METHOD(thread_i_0_i_i_c_din);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( i_0_i_i_c_full_n );
    sensitive << ( imatrix_offset_out_full_n );
    sensitive << ( omatrix_offset_out_full_n );
    sensitive << ( tmp_fu_589_p1 );

    SC_METHOD(thread_i_0_i_i_c_write);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( i_0_i_i_c_full_n );
    sensitive << ( imatrix_offset_out_full_n );
    sensitive << ( omatrix_offset_out_full_n );

    SC_METHOD(thread_imatrix_offset_out_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( imatrix_offset_out_full_n );

    SC_METHOD(thread_imatrix_offset_out_din);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( i_0_i_i_c_full_n );
    sensitive << ( imatrix_offset );
    sensitive << ( imatrix_offset_out_full_n );
    sensitive << ( omatrix_offset_out_full_n );

    SC_METHOD(thread_imatrix_offset_out_write);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( i_0_i_i_c_full_n );
    sensitive << ( imatrix_offset_out_full_n );
    sensitive << ( omatrix_offset_out_full_n );

    SC_METHOD(thread_in1_buf_0_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( newIndex1_i_i_i_i_i_fu_908_p1 );

    SC_METHOD(thread_in1_buf_0_ce0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_0_d0);
    sensitive << ( zigzag_index_q0 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_0_we0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_10_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( newIndex1_i_i_i_i_i_fu_908_p1 );

    SC_METHOD(thread_in1_buf_10_ce0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_10_d0);
    sensitive << ( zigzag_index_q10 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_10_we0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_11_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( newIndex1_i_i_i_i_i_fu_908_p1 );

    SC_METHOD(thread_in1_buf_11_ce0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_11_d0);
    sensitive << ( zigzag_index_q11 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_11_we0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_12_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( newIndex1_i_i_i_i_i_fu_908_p1 );

    SC_METHOD(thread_in1_buf_12_ce0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_12_d0);
    sensitive << ( zigzag_index_q12 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_12_we0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_13_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( newIndex1_i_i_i_i_i_fu_908_p1 );

    SC_METHOD(thread_in1_buf_13_ce0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_13_d0);
    sensitive << ( zigzag_index_q13 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_13_we0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_14_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( newIndex1_i_i_i_i_i_fu_908_p1 );

    SC_METHOD(thread_in1_buf_14_ce0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_14_d0);
    sensitive << ( zigzag_index_q14 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_14_we0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_15_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( newIndex1_i_i_i_i_i_fu_908_p1 );

    SC_METHOD(thread_in1_buf_15_ce0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_15_d0);
    sensitive << ( zigzag_index_q15 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_15_we0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_1_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( newIndex1_i_i_i_i_i_fu_908_p1 );

    SC_METHOD(thread_in1_buf_1_ce0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_1_d0);
    sensitive << ( zigzag_index_q1 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_1_we0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_2_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( newIndex1_i_i_i_i_i_fu_908_p1 );

    SC_METHOD(thread_in1_buf_2_ce0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_2_d0);
    sensitive << ( zigzag_index_q2 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_2_we0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_3_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( newIndex1_i_i_i_i_i_fu_908_p1 );

    SC_METHOD(thread_in1_buf_3_ce0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_3_d0);
    sensitive << ( zigzag_index_q3 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_3_we0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_4_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( newIndex1_i_i_i_i_i_fu_908_p1 );

    SC_METHOD(thread_in1_buf_4_ce0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_4_d0);
    sensitive << ( zigzag_index_q4 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_4_we0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_5_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( newIndex1_i_i_i_i_i_fu_908_p1 );

    SC_METHOD(thread_in1_buf_5_ce0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_5_d0);
    sensitive << ( zigzag_index_q5 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_5_we0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_6_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( newIndex1_i_i_i_i_i_fu_908_p1 );

    SC_METHOD(thread_in1_buf_6_ce0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_6_d0);
    sensitive << ( zigzag_index_q6 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_6_we0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_7_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( newIndex1_i_i_i_i_i_fu_908_p1 );

    SC_METHOD(thread_in1_buf_7_ce0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_7_d0);
    sensitive << ( zigzag_index_q7 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_7_we0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_8_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( newIndex1_i_i_i_i_i_fu_908_p1 );

    SC_METHOD(thread_in1_buf_8_ce0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_8_d0);
    sensitive << ( zigzag_index_q8 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_8_we0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_9_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( newIndex1_i_i_i_i_i_fu_908_p1 );

    SC_METHOD(thread_in1_buf_9_ce0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_9_d0);
    sensitive << ( zigzag_index_q9 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in1_buf_9_we0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_j_i_15_i_i_i_i_i_fu_902_p2);
    sensitive << ( j_0_i_i_i_i_i_i_i_reg_578 );

    SC_METHOD(thread_newIndex1_i_i_i_i_i_fu_908_p1);
    sensitive << ( newIndex_i_i_i_i_i_reg_959 );

    SC_METHOD(thread_offset_i_10_i_i_i_i_s_fu_818_p3);
    sensitive << ( tmp_reg_927 );
    sensitive << ( tmp_i_i_i_21_fu_812_p2 );

    SC_METHOD(thread_offset_i_11_i_i_i_i_s_fu_836_p3);
    sensitive << ( tmp_reg_927 );
    sensitive << ( tmp_10_i_i_i_fu_830_p2 );

    SC_METHOD(thread_offset_i_12_i_i_i_i_s_fu_854_p3);
    sensitive << ( tmp_reg_927 );
    sensitive << ( tmp_11_i_i_i_fu_848_p2 );

    SC_METHOD(thread_offset_i_13_i_i_i_i_s_fu_872_p3);
    sensitive << ( tmp_reg_927 );
    sensitive << ( tmp_12_i_i_i_fu_866_p2 );

    SC_METHOD(thread_offset_i_14_i_i_i_i_s_fu_890_p3);
    sensitive << ( tmp_reg_927 );
    sensitive << ( tmp_13_i_i_i_fu_884_p2 );

    SC_METHOD(thread_offset_i_1_i_i_i_i_i_fu_638_p3);
    sensitive << ( tmp_reg_927 );
    sensitive << ( tmp_i_i_i_fu_632_p2 );

    SC_METHOD(thread_offset_i_2_i_i_i_i_i_fu_656_p3);
    sensitive << ( tmp_reg_927 );
    sensitive << ( tmp_1_i_i_i_fu_650_p2 );

    SC_METHOD(thread_offset_i_3_i_i_i_i_i_fu_674_p3);
    sensitive << ( tmp_reg_927 );
    sensitive << ( tmp_2_i_i_i_fu_668_p2 );

    SC_METHOD(thread_offset_i_4_i_i_i_i_i_fu_692_p3);
    sensitive << ( tmp_reg_927 );
    sensitive << ( tmp_3_i_i_i_fu_686_p2 );

    SC_METHOD(thread_offset_i_5_i_i_i_i_i_fu_710_p3);
    sensitive << ( tmp_reg_927 );
    sensitive << ( tmp_4_i_i_i_fu_704_p2 );

    SC_METHOD(thread_offset_i_6_i_i_i_i_i_fu_728_p3);
    sensitive << ( tmp_reg_927 );
    sensitive << ( tmp_5_i_i_i_fu_722_p2 );

    SC_METHOD(thread_offset_i_7_i_i_i_i_i_fu_746_p3);
    sensitive << ( tmp_reg_927 );
    sensitive << ( tmp_6_i_i_i_fu_740_p2 );

    SC_METHOD(thread_offset_i_8_i_i_i_i_i_fu_764_p3);
    sensitive << ( tmp_reg_927 );
    sensitive << ( tmp_7_i_i_i_fu_758_p2 );

    SC_METHOD(thread_offset_i_9_i_i_i_i_i_fu_782_p3);
    sensitive << ( tmp_reg_927 );
    sensitive << ( tmp_8_i_i_i_fu_776_p2 );

    SC_METHOD(thread_offset_i_i_i_i_fu_594_p3);
    sensitive << ( tmp_fu_589_p1 );

    SC_METHOD(thread_offset_i_i_i_i_i_i_19_fu_800_p3);
    sensitive << ( tmp_reg_927 );
    sensitive << ( tmp_9_i_i_i_fu_794_p2 );

    SC_METHOD(thread_offset_i_i_i_i_i_i_fu_608_p2);
    sensitive << ( offset_i_i_i_i_reg_946 );
    sensitive << ( j_0_i_i_i_i_i_i_i_reg_578 );

    SC_METHOD(thread_omatrix_offset_out_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( omatrix_offset_out_full_n );

    SC_METHOD(thread_omatrix_offset_out_din);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( i_0_i_i_c_full_n );
    sensitive << ( omatrix_offset );
    sensitive << ( imatrix_offset_out_full_n );
    sensitive << ( omatrix_offset_out_full_n );

    SC_METHOD(thread_omatrix_offset_out_write);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( i_0_i_i_c_full_n );
    sensitive << ( imatrix_offset_out_full_n );
    sensitive << ( omatrix_offset_out_full_n );

    SC_METHOD(thread_tmp_10_i_i_i_fu_830_p2);
    sensitive << ( tmp_1_fu_628_p1 );

    SC_METHOD(thread_tmp_11_i_i_i_fu_848_p2);
    sensitive << ( tmp_1_fu_628_p1 );

    SC_METHOD(thread_tmp_12_i_i_i_fu_866_p2);
    sensitive << ( tmp_1_fu_628_p1 );

    SC_METHOD(thread_tmp_13_i_i_i_fu_884_p2);
    sensitive << ( tmp_1_fu_628_p1 );

    SC_METHOD(thread_tmp_1_fu_628_p1);
    sensitive << ( j_0_i_i_i_i_i_i_i_reg_578 );

    SC_METHOD(thread_tmp_1_i_10_i_i_i_i_i_fu_825_p1);
    sensitive << ( offset_i_10_i_i_i_i_s_fu_818_p3 );

    SC_METHOD(thread_tmp_1_i_11_i_i_i_i_i_fu_843_p1);
    sensitive << ( offset_i_11_i_i_i_i_s_fu_836_p3 );

    SC_METHOD(thread_tmp_1_i_12_i_i_i_i_i_fu_861_p1);
    sensitive << ( offset_i_12_i_i_i_i_s_fu_854_p3 );

    SC_METHOD(thread_tmp_1_i_13_i_i_i_i_i_fu_879_p1);
    sensitive << ( offset_i_13_i_i_i_i_s_fu_872_p3 );

    SC_METHOD(thread_tmp_1_i_14_i_i_i_i_i_fu_897_p1);
    sensitive << ( offset_i_14_i_i_i_i_s_fu_890_p3 );

    SC_METHOD(thread_tmp_1_i_1_i_i_i_i_i_fu_645_p1);
    sensitive << ( offset_i_1_i_i_i_i_i_fu_638_p3 );

    SC_METHOD(thread_tmp_1_i_2_i_i_i_i_i_fu_663_p1);
    sensitive << ( offset_i_2_i_i_i_i_i_fu_656_p3 );

    SC_METHOD(thread_tmp_1_i_3_i_i_i_i_i_fu_681_p1);
    sensitive << ( offset_i_3_i_i_i_i_i_fu_674_p3 );

    SC_METHOD(thread_tmp_1_i_4_i_i_i_i_i_fu_699_p1);
    sensitive << ( offset_i_4_i_i_i_i_i_fu_692_p3 );

    SC_METHOD(thread_tmp_1_i_5_i_i_i_i_i_fu_717_p1);
    sensitive << ( offset_i_5_i_i_i_i_i_fu_710_p3 );

    SC_METHOD(thread_tmp_1_i_6_i_i_i_i_i_fu_735_p1);
    sensitive << ( offset_i_6_i_i_i_i_i_fu_728_p3 );

    SC_METHOD(thread_tmp_1_i_7_i_i_i_i_i_fu_753_p1);
    sensitive << ( offset_i_7_i_i_i_i_i_fu_746_p3 );

    SC_METHOD(thread_tmp_1_i_8_i_i_i_i_i_fu_771_p1);
    sensitive << ( offset_i_8_i_i_i_i_i_fu_764_p3 );

    SC_METHOD(thread_tmp_1_i_9_i_i_i_i_i_fu_789_p1);
    sensitive << ( offset_i_9_i_i_i_i_i_fu_782_p3 );

    SC_METHOD(thread_tmp_1_i_i_i_fu_650_p2);
    sensitive << ( tmp_1_fu_628_p1 );

    SC_METHOD(thread_tmp_1_i_i_i_i_i_i_20_fu_807_p1);
    sensitive << ( offset_i_i_i_i_i_i_19_fu_800_p3 );

    SC_METHOD(thread_tmp_1_i_i_i_i_i_i_fu_613_p1);
    sensitive << ( offset_i_i_i_i_i_i_fu_608_p2 );

    SC_METHOD(thread_tmp_2_i_i_i_fu_668_p2);
    sensitive << ( tmp_1_fu_628_p1 );

    SC_METHOD(thread_tmp_3_i_i_i_fu_686_p2);
    sensitive << ( tmp_1_fu_628_p1 );

    SC_METHOD(thread_tmp_4_i_i_i_fu_704_p2);
    sensitive << ( tmp_1_fu_628_p1 );

    SC_METHOD(thread_tmp_5_i_i_i_fu_722_p2);
    sensitive << ( tmp_1_fu_628_p1 );

    SC_METHOD(thread_tmp_6_i_i_i_fu_740_p2);
    sensitive << ( tmp_1_fu_628_p1 );

    SC_METHOD(thread_tmp_7_i_i_i_fu_758_p2);
    sensitive << ( tmp_1_fu_628_p1 );

    SC_METHOD(thread_tmp_8_i_i_i_fu_776_p2);
    sensitive << ( tmp_1_fu_628_p1 );

    SC_METHOD(thread_tmp_9_i_i_i_fu_794_p2);
    sensitive << ( tmp_1_fu_628_p1 );

    SC_METHOD(thread_tmp_fu_589_p1);
    sensitive << ( i_0_i_i );

    SC_METHOD(thread_tmp_i_i_i_21_fu_812_p2);
    sensitive << ( tmp_1_fu_628_p1 );

    SC_METHOD(thread_tmp_i_i_i_fu_632_p2);
    sensitive << ( tmp_1_fu_628_p1 );

    SC_METHOD(thread_zigzag_index_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_1_i_i_i_i_i_i_fu_613_p1 );

    SC_METHOD(thread_zigzag_index_address1);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_1_i_1_i_i_i_i_i_fu_645_p1 );

    SC_METHOD(thread_zigzag_index_address10);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_1_i_i_i_i_i_i_20_fu_807_p1 );

    SC_METHOD(thread_zigzag_index_address11);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_1_i_10_i_i_i_i_i_fu_825_p1 );

    SC_METHOD(thread_zigzag_index_address12);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_1_i_11_i_i_i_i_i_fu_843_p1 );

    SC_METHOD(thread_zigzag_index_address13);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_1_i_12_i_i_i_i_i_fu_861_p1 );

    SC_METHOD(thread_zigzag_index_address14);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_1_i_13_i_i_i_i_i_fu_879_p1 );

    SC_METHOD(thread_zigzag_index_address15);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_1_i_14_i_i_i_i_i_fu_897_p1 );

    SC_METHOD(thread_zigzag_index_address2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_1_i_2_i_i_i_i_i_fu_663_p1 );

    SC_METHOD(thread_zigzag_index_address3);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_1_i_3_i_i_i_i_i_fu_681_p1 );

    SC_METHOD(thread_zigzag_index_address4);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_1_i_4_i_i_i_i_i_fu_699_p1 );

    SC_METHOD(thread_zigzag_index_address5);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_1_i_5_i_i_i_i_i_fu_717_p1 );

    SC_METHOD(thread_zigzag_index_address6);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_1_i_6_i_i_i_i_i_fu_735_p1 );

    SC_METHOD(thread_zigzag_index_address7);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_1_i_7_i_i_i_i_i_fu_753_p1 );

    SC_METHOD(thread_zigzag_index_address8);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_1_i_8_i_i_i_i_i_fu_771_p1 );

    SC_METHOD(thread_zigzag_index_address9);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_1_i_9_i_i_i_i_i_fu_789_p1 );

    SC_METHOD(thread_zigzag_index_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_zigzag_index_ce1);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_zigzag_index_ce10);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_zigzag_index_ce11);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_zigzag_index_ce12);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_zigzag_index_ce13);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_zigzag_index_ce14);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_zigzag_index_ce15);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_zigzag_index_ce2);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_zigzag_index_ce3);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_zigzag_index_ce4);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_zigzag_index_ce5);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_zigzag_index_ce6);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_zigzag_index_ce7);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_zigzag_index_ce8);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_zigzag_index_ce9);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( i_0_i_i_c_full_n );
    sensitive << ( imatrix_offset_out_full_n );
    sensitive << ( omatrix_offset_out_full_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_i_i_i_i_i_s_fu_602_p2 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "Loop_0_proc19_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, i_0_i_i, "(port)i_0_i_i");
    sc_trace(mVcdFile, in1_buf_0_address0, "(port)in1_buf_0_address0");
    sc_trace(mVcdFile, in1_buf_0_ce0, "(port)in1_buf_0_ce0");
    sc_trace(mVcdFile, in1_buf_0_we0, "(port)in1_buf_0_we0");
    sc_trace(mVcdFile, in1_buf_0_d0, "(port)in1_buf_0_d0");
    sc_trace(mVcdFile, in1_buf_1_address0, "(port)in1_buf_1_address0");
    sc_trace(mVcdFile, in1_buf_1_ce0, "(port)in1_buf_1_ce0");
    sc_trace(mVcdFile, in1_buf_1_we0, "(port)in1_buf_1_we0");
    sc_trace(mVcdFile, in1_buf_1_d0, "(port)in1_buf_1_d0");
    sc_trace(mVcdFile, in1_buf_2_address0, "(port)in1_buf_2_address0");
    sc_trace(mVcdFile, in1_buf_2_ce0, "(port)in1_buf_2_ce0");
    sc_trace(mVcdFile, in1_buf_2_we0, "(port)in1_buf_2_we0");
    sc_trace(mVcdFile, in1_buf_2_d0, "(port)in1_buf_2_d0");
    sc_trace(mVcdFile, in1_buf_3_address0, "(port)in1_buf_3_address0");
    sc_trace(mVcdFile, in1_buf_3_ce0, "(port)in1_buf_3_ce0");
    sc_trace(mVcdFile, in1_buf_3_we0, "(port)in1_buf_3_we0");
    sc_trace(mVcdFile, in1_buf_3_d0, "(port)in1_buf_3_d0");
    sc_trace(mVcdFile, in1_buf_4_address0, "(port)in1_buf_4_address0");
    sc_trace(mVcdFile, in1_buf_4_ce0, "(port)in1_buf_4_ce0");
    sc_trace(mVcdFile, in1_buf_4_we0, "(port)in1_buf_4_we0");
    sc_trace(mVcdFile, in1_buf_4_d0, "(port)in1_buf_4_d0");
    sc_trace(mVcdFile, in1_buf_5_address0, "(port)in1_buf_5_address0");
    sc_trace(mVcdFile, in1_buf_5_ce0, "(port)in1_buf_5_ce0");
    sc_trace(mVcdFile, in1_buf_5_we0, "(port)in1_buf_5_we0");
    sc_trace(mVcdFile, in1_buf_5_d0, "(port)in1_buf_5_d0");
    sc_trace(mVcdFile, in1_buf_6_address0, "(port)in1_buf_6_address0");
    sc_trace(mVcdFile, in1_buf_6_ce0, "(port)in1_buf_6_ce0");
    sc_trace(mVcdFile, in1_buf_6_we0, "(port)in1_buf_6_we0");
    sc_trace(mVcdFile, in1_buf_6_d0, "(port)in1_buf_6_d0");
    sc_trace(mVcdFile, in1_buf_7_address0, "(port)in1_buf_7_address0");
    sc_trace(mVcdFile, in1_buf_7_ce0, "(port)in1_buf_7_ce0");
    sc_trace(mVcdFile, in1_buf_7_we0, "(port)in1_buf_7_we0");
    sc_trace(mVcdFile, in1_buf_7_d0, "(port)in1_buf_7_d0");
    sc_trace(mVcdFile, in1_buf_8_address0, "(port)in1_buf_8_address0");
    sc_trace(mVcdFile, in1_buf_8_ce0, "(port)in1_buf_8_ce0");
    sc_trace(mVcdFile, in1_buf_8_we0, "(port)in1_buf_8_we0");
    sc_trace(mVcdFile, in1_buf_8_d0, "(port)in1_buf_8_d0");
    sc_trace(mVcdFile, in1_buf_9_address0, "(port)in1_buf_9_address0");
    sc_trace(mVcdFile, in1_buf_9_ce0, "(port)in1_buf_9_ce0");
    sc_trace(mVcdFile, in1_buf_9_we0, "(port)in1_buf_9_we0");
    sc_trace(mVcdFile, in1_buf_9_d0, "(port)in1_buf_9_d0");
    sc_trace(mVcdFile, in1_buf_10_address0, "(port)in1_buf_10_address0");
    sc_trace(mVcdFile, in1_buf_10_ce0, "(port)in1_buf_10_ce0");
    sc_trace(mVcdFile, in1_buf_10_we0, "(port)in1_buf_10_we0");
    sc_trace(mVcdFile, in1_buf_10_d0, "(port)in1_buf_10_d0");
    sc_trace(mVcdFile, in1_buf_11_address0, "(port)in1_buf_11_address0");
    sc_trace(mVcdFile, in1_buf_11_ce0, "(port)in1_buf_11_ce0");
    sc_trace(mVcdFile, in1_buf_11_we0, "(port)in1_buf_11_we0");
    sc_trace(mVcdFile, in1_buf_11_d0, "(port)in1_buf_11_d0");
    sc_trace(mVcdFile, in1_buf_12_address0, "(port)in1_buf_12_address0");
    sc_trace(mVcdFile, in1_buf_12_ce0, "(port)in1_buf_12_ce0");
    sc_trace(mVcdFile, in1_buf_12_we0, "(port)in1_buf_12_we0");
    sc_trace(mVcdFile, in1_buf_12_d0, "(port)in1_buf_12_d0");
    sc_trace(mVcdFile, in1_buf_13_address0, "(port)in1_buf_13_address0");
    sc_trace(mVcdFile, in1_buf_13_ce0, "(port)in1_buf_13_ce0");
    sc_trace(mVcdFile, in1_buf_13_we0, "(port)in1_buf_13_we0");
    sc_trace(mVcdFile, in1_buf_13_d0, "(port)in1_buf_13_d0");
    sc_trace(mVcdFile, in1_buf_14_address0, "(port)in1_buf_14_address0");
    sc_trace(mVcdFile, in1_buf_14_ce0, "(port)in1_buf_14_ce0");
    sc_trace(mVcdFile, in1_buf_14_we0, "(port)in1_buf_14_we0");
    sc_trace(mVcdFile, in1_buf_14_d0, "(port)in1_buf_14_d0");
    sc_trace(mVcdFile, in1_buf_15_address0, "(port)in1_buf_15_address0");
    sc_trace(mVcdFile, in1_buf_15_ce0, "(port)in1_buf_15_ce0");
    sc_trace(mVcdFile, in1_buf_15_we0, "(port)in1_buf_15_we0");
    sc_trace(mVcdFile, in1_buf_15_d0, "(port)in1_buf_15_d0");
    sc_trace(mVcdFile, i_0_i_i_c_din, "(port)i_0_i_i_c_din");
    sc_trace(mVcdFile, i_0_i_i_c_full_n, "(port)i_0_i_i_c_full_n");
    sc_trace(mVcdFile, i_0_i_i_c_write, "(port)i_0_i_i_c_write");
    sc_trace(mVcdFile, imatrix_offset, "(port)imatrix_offset");
    sc_trace(mVcdFile, omatrix_offset, "(port)omatrix_offset");
    sc_trace(mVcdFile, imatrix_offset_out_din, "(port)imatrix_offset_out_din");
    sc_trace(mVcdFile, imatrix_offset_out_full_n, "(port)imatrix_offset_out_full_n");
    sc_trace(mVcdFile, imatrix_offset_out_write, "(port)imatrix_offset_out_write");
    sc_trace(mVcdFile, omatrix_offset_out_din, "(port)omatrix_offset_out_din");
    sc_trace(mVcdFile, omatrix_offset_out_full_n, "(port)omatrix_offset_out_full_n");
    sc_trace(mVcdFile, omatrix_offset_out_write, "(port)omatrix_offset_out_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, zigzag_index_address0, "zigzag_index_address0");
    sc_trace(mVcdFile, zigzag_index_ce0, "zigzag_index_ce0");
    sc_trace(mVcdFile, zigzag_index_q0, "zigzag_index_q0");
    sc_trace(mVcdFile, zigzag_index_address1, "zigzag_index_address1");
    sc_trace(mVcdFile, zigzag_index_ce1, "zigzag_index_ce1");
    sc_trace(mVcdFile, zigzag_index_q1, "zigzag_index_q1");
    sc_trace(mVcdFile, zigzag_index_address2, "zigzag_index_address2");
    sc_trace(mVcdFile, zigzag_index_ce2, "zigzag_index_ce2");
    sc_trace(mVcdFile, zigzag_index_q2, "zigzag_index_q2");
    sc_trace(mVcdFile, zigzag_index_address3, "zigzag_index_address3");
    sc_trace(mVcdFile, zigzag_index_ce3, "zigzag_index_ce3");
    sc_trace(mVcdFile, zigzag_index_q3, "zigzag_index_q3");
    sc_trace(mVcdFile, zigzag_index_address4, "zigzag_index_address4");
    sc_trace(mVcdFile, zigzag_index_ce4, "zigzag_index_ce4");
    sc_trace(mVcdFile, zigzag_index_q4, "zigzag_index_q4");
    sc_trace(mVcdFile, zigzag_index_address5, "zigzag_index_address5");
    sc_trace(mVcdFile, zigzag_index_ce5, "zigzag_index_ce5");
    sc_trace(mVcdFile, zigzag_index_q5, "zigzag_index_q5");
    sc_trace(mVcdFile, zigzag_index_address6, "zigzag_index_address6");
    sc_trace(mVcdFile, zigzag_index_ce6, "zigzag_index_ce6");
    sc_trace(mVcdFile, zigzag_index_q6, "zigzag_index_q6");
    sc_trace(mVcdFile, zigzag_index_address7, "zigzag_index_address7");
    sc_trace(mVcdFile, zigzag_index_ce7, "zigzag_index_ce7");
    sc_trace(mVcdFile, zigzag_index_q7, "zigzag_index_q7");
    sc_trace(mVcdFile, zigzag_index_address8, "zigzag_index_address8");
    sc_trace(mVcdFile, zigzag_index_ce8, "zigzag_index_ce8");
    sc_trace(mVcdFile, zigzag_index_q8, "zigzag_index_q8");
    sc_trace(mVcdFile, zigzag_index_address9, "zigzag_index_address9");
    sc_trace(mVcdFile, zigzag_index_ce9, "zigzag_index_ce9");
    sc_trace(mVcdFile, zigzag_index_q9, "zigzag_index_q9");
    sc_trace(mVcdFile, zigzag_index_address10, "zigzag_index_address10");
    sc_trace(mVcdFile, zigzag_index_ce10, "zigzag_index_ce10");
    sc_trace(mVcdFile, zigzag_index_q10, "zigzag_index_q10");
    sc_trace(mVcdFile, zigzag_index_address11, "zigzag_index_address11");
    sc_trace(mVcdFile, zigzag_index_ce11, "zigzag_index_ce11");
    sc_trace(mVcdFile, zigzag_index_q11, "zigzag_index_q11");
    sc_trace(mVcdFile, zigzag_index_address12, "zigzag_index_address12");
    sc_trace(mVcdFile, zigzag_index_ce12, "zigzag_index_ce12");
    sc_trace(mVcdFile, zigzag_index_q12, "zigzag_index_q12");
    sc_trace(mVcdFile, zigzag_index_address13, "zigzag_index_address13");
    sc_trace(mVcdFile, zigzag_index_ce13, "zigzag_index_ce13");
    sc_trace(mVcdFile, zigzag_index_q13, "zigzag_index_q13");
    sc_trace(mVcdFile, zigzag_index_address14, "zigzag_index_address14");
    sc_trace(mVcdFile, zigzag_index_ce14, "zigzag_index_ce14");
    sc_trace(mVcdFile, zigzag_index_q14, "zigzag_index_q14");
    sc_trace(mVcdFile, zigzag_index_address15, "zigzag_index_address15");
    sc_trace(mVcdFile, zigzag_index_ce15, "zigzag_index_ce15");
    sc_trace(mVcdFile, zigzag_index_q15, "zigzag_index_q15");
    sc_trace(mVcdFile, i_0_i_i_c_blk_n, "i_0_i_i_c_blk_n");
    sc_trace(mVcdFile, imatrix_offset_out_blk_n, "imatrix_offset_out_blk_n");
    sc_trace(mVcdFile, omatrix_offset_out_blk_n, "omatrix_offset_out_blk_n");
    sc_trace(mVcdFile, tmp_fu_589_p1, "tmp_fu_589_p1");
    sc_trace(mVcdFile, tmp_reg_927, "tmp_reg_927");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, offset_i_i_i_i_fu_594_p3, "offset_i_i_i_i_fu_594_p3");
    sc_trace(mVcdFile, offset_i_i_i_i_reg_946, "offset_i_i_i_i_reg_946");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, exitcond1_i_i_i_i_i_s_fu_602_p2, "exitcond1_i_i_i_i_i_s_fu_602_p2");
    sc_trace(mVcdFile, newIndex_i_i_i_i_i_reg_959, "newIndex_i_i_i_i_i_reg_959");
    sc_trace(mVcdFile, j_i_15_i_i_i_i_i_fu_902_p2, "j_i_15_i_i_i_i_i_fu_902_p2");
    sc_trace(mVcdFile, j_i_15_i_i_i_i_i_reg_1039, "j_i_15_i_i_i_i_i_reg_1039");
    sc_trace(mVcdFile, j_0_i_i_i_i_i_i_i_reg_578, "j_0_i_i_i_i_i_i_i_reg_578");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, tmp_1_i_i_i_i_i_i_fu_613_p1, "tmp_1_i_i_i_i_i_i_fu_613_p1");
    sc_trace(mVcdFile, tmp_1_i_1_i_i_i_i_i_fu_645_p1, "tmp_1_i_1_i_i_i_i_i_fu_645_p1");
    sc_trace(mVcdFile, tmp_1_i_2_i_i_i_i_i_fu_663_p1, "tmp_1_i_2_i_i_i_i_i_fu_663_p1");
    sc_trace(mVcdFile, tmp_1_i_3_i_i_i_i_i_fu_681_p1, "tmp_1_i_3_i_i_i_i_i_fu_681_p1");
    sc_trace(mVcdFile, tmp_1_i_4_i_i_i_i_i_fu_699_p1, "tmp_1_i_4_i_i_i_i_i_fu_699_p1");
    sc_trace(mVcdFile, tmp_1_i_5_i_i_i_i_i_fu_717_p1, "tmp_1_i_5_i_i_i_i_i_fu_717_p1");
    sc_trace(mVcdFile, tmp_1_i_6_i_i_i_i_i_fu_735_p1, "tmp_1_i_6_i_i_i_i_i_fu_735_p1");
    sc_trace(mVcdFile, tmp_1_i_7_i_i_i_i_i_fu_753_p1, "tmp_1_i_7_i_i_i_i_i_fu_753_p1");
    sc_trace(mVcdFile, tmp_1_i_8_i_i_i_i_i_fu_771_p1, "tmp_1_i_8_i_i_i_i_i_fu_771_p1");
    sc_trace(mVcdFile, tmp_1_i_9_i_i_i_i_i_fu_789_p1, "tmp_1_i_9_i_i_i_i_i_fu_789_p1");
    sc_trace(mVcdFile, tmp_1_i_i_i_i_i_i_20_fu_807_p1, "tmp_1_i_i_i_i_i_i_20_fu_807_p1");
    sc_trace(mVcdFile, tmp_1_i_10_i_i_i_i_i_fu_825_p1, "tmp_1_i_10_i_i_i_i_i_fu_825_p1");
    sc_trace(mVcdFile, tmp_1_i_11_i_i_i_i_i_fu_843_p1, "tmp_1_i_11_i_i_i_i_i_fu_843_p1");
    sc_trace(mVcdFile, tmp_1_i_12_i_i_i_i_i_fu_861_p1, "tmp_1_i_12_i_i_i_i_i_fu_861_p1");
    sc_trace(mVcdFile, tmp_1_i_13_i_i_i_i_i_fu_879_p1, "tmp_1_i_13_i_i_i_i_i_fu_879_p1");
    sc_trace(mVcdFile, tmp_1_i_14_i_i_i_i_i_fu_897_p1, "tmp_1_i_14_i_i_i_i_i_fu_897_p1");
    sc_trace(mVcdFile, newIndex1_i_i_i_i_i_fu_908_p1, "newIndex1_i_i_i_i_i_fu_908_p1");
    sc_trace(mVcdFile, offset_i_i_i_i_i_i_fu_608_p2, "offset_i_i_i_i_i_i_fu_608_p2");
    sc_trace(mVcdFile, tmp_1_fu_628_p1, "tmp_1_fu_628_p1");
    sc_trace(mVcdFile, tmp_i_i_i_fu_632_p2, "tmp_i_i_i_fu_632_p2");
    sc_trace(mVcdFile, offset_i_1_i_i_i_i_i_fu_638_p3, "offset_i_1_i_i_i_i_i_fu_638_p3");
    sc_trace(mVcdFile, tmp_1_i_i_i_fu_650_p2, "tmp_1_i_i_i_fu_650_p2");
    sc_trace(mVcdFile, offset_i_2_i_i_i_i_i_fu_656_p3, "offset_i_2_i_i_i_i_i_fu_656_p3");
    sc_trace(mVcdFile, tmp_2_i_i_i_fu_668_p2, "tmp_2_i_i_i_fu_668_p2");
    sc_trace(mVcdFile, offset_i_3_i_i_i_i_i_fu_674_p3, "offset_i_3_i_i_i_i_i_fu_674_p3");
    sc_trace(mVcdFile, tmp_3_i_i_i_fu_686_p2, "tmp_3_i_i_i_fu_686_p2");
    sc_trace(mVcdFile, offset_i_4_i_i_i_i_i_fu_692_p3, "offset_i_4_i_i_i_i_i_fu_692_p3");
    sc_trace(mVcdFile, tmp_4_i_i_i_fu_704_p2, "tmp_4_i_i_i_fu_704_p2");
    sc_trace(mVcdFile, offset_i_5_i_i_i_i_i_fu_710_p3, "offset_i_5_i_i_i_i_i_fu_710_p3");
    sc_trace(mVcdFile, tmp_5_i_i_i_fu_722_p2, "tmp_5_i_i_i_fu_722_p2");
    sc_trace(mVcdFile, offset_i_6_i_i_i_i_i_fu_728_p3, "offset_i_6_i_i_i_i_i_fu_728_p3");
    sc_trace(mVcdFile, tmp_6_i_i_i_fu_740_p2, "tmp_6_i_i_i_fu_740_p2");
    sc_trace(mVcdFile, offset_i_7_i_i_i_i_i_fu_746_p3, "offset_i_7_i_i_i_i_i_fu_746_p3");
    sc_trace(mVcdFile, tmp_7_i_i_i_fu_758_p2, "tmp_7_i_i_i_fu_758_p2");
    sc_trace(mVcdFile, offset_i_8_i_i_i_i_i_fu_764_p3, "offset_i_8_i_i_i_i_i_fu_764_p3");
    sc_trace(mVcdFile, tmp_8_i_i_i_fu_776_p2, "tmp_8_i_i_i_fu_776_p2");
    sc_trace(mVcdFile, offset_i_9_i_i_i_i_i_fu_782_p3, "offset_i_9_i_i_i_i_i_fu_782_p3");
    sc_trace(mVcdFile, tmp_9_i_i_i_fu_794_p2, "tmp_9_i_i_i_fu_794_p2");
    sc_trace(mVcdFile, offset_i_i_i_i_i_i_19_fu_800_p3, "offset_i_i_i_i_i_i_19_fu_800_p3");
    sc_trace(mVcdFile, tmp_i_i_i_21_fu_812_p2, "tmp_i_i_i_21_fu_812_p2");
    sc_trace(mVcdFile, offset_i_10_i_i_i_i_s_fu_818_p3, "offset_i_10_i_i_i_i_s_fu_818_p3");
    sc_trace(mVcdFile, tmp_10_i_i_i_fu_830_p2, "tmp_10_i_i_i_fu_830_p2");
    sc_trace(mVcdFile, offset_i_11_i_i_i_i_s_fu_836_p3, "offset_i_11_i_i_i_i_s_fu_836_p3");
    sc_trace(mVcdFile, tmp_11_i_i_i_fu_848_p2, "tmp_11_i_i_i_fu_848_p2");
    sc_trace(mVcdFile, offset_i_12_i_i_i_i_s_fu_854_p3, "offset_i_12_i_i_i_i_s_fu_854_p3");
    sc_trace(mVcdFile, tmp_12_i_i_i_fu_866_p2, "tmp_12_i_i_i_fu_866_p2");
    sc_trace(mVcdFile, offset_i_13_i_i_i_i_s_fu_872_p3, "offset_i_13_i_i_i_i_s_fu_872_p3");
    sc_trace(mVcdFile, tmp_13_i_i_i_fu_884_p2, "tmp_13_i_i_i_fu_884_p2");
    sc_trace(mVcdFile, offset_i_14_i_i_i_i_s_fu_890_p3, "offset_i_14_i_i_i_i_s_fu_890_p3");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

Loop_0_proc19::~Loop_0_proc19() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete zigzag_index_U;
}

void Loop_0_proc19::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(exitcond1_i_i_i_i_i_s_fu_602_p2.read(), ap_const_lv1_1))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        j_0_i_i_i_i_i_i_i_reg_578 = j_i_15_i_i_i_i_i_reg_1039.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, imatrix_offset_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, omatrix_offset_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, i_0_i_i_c_full_n.read())))) {
        j_0_i_i_i_i_i_i_i_reg_578 = ap_const_lv6_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond1_i_i_i_i_i_s_fu_602_p2.read(), ap_const_lv1_0))) {
        j_i_15_i_i_i_i_i_reg_1039 = j_i_15_i_i_i_i_i_fu_902_p2.read();
        newIndex_i_i_i_i_i_reg_959 = j_0_i_i_i_i_i_i_i_reg_578.read().range(5, 4);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, imatrix_offset_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, omatrix_offset_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, i_0_i_i_c_full_n.read())))) {
        offset_i_i_i_i_reg_946 = offset_i_i_i_i_fu_594_p3.read();
        tmp_reg_927 = tmp_fu_589_p1.read();
    }
}

void Loop_0_proc19::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void Loop_0_proc19::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void Loop_0_proc19::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void Loop_0_proc19::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, imatrix_offset_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, omatrix_offset_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, i_0_i_i_c_full_n.read()));
}

void Loop_0_proc19::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond1_i_i_i_i_i_s_fu_602_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void Loop_0_proc19::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond1_i_i_i_i_i_s_fu_602_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_exitcond1_i_i_i_i_i_s_fu_602_p2() {
    exitcond1_i_i_i_i_i_s_fu_602_p2 = (!j_0_i_i_i_i_i_i_i_reg_578.read().is_01() || !ap_const_lv6_20.is_01())? sc_lv<1>(): sc_lv<1>(j_0_i_i_i_i_i_i_i_reg_578.read() == ap_const_lv6_20);
}

void Loop_0_proc19::thread_i_0_i_i_c_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        i_0_i_i_c_blk_n = i_0_i_i_c_full_n.read();
    } else {
        i_0_i_i_c_blk_n = ap_const_logic_1;
    }
}

void Loop_0_proc19::thread_i_0_i_i_c_din() {
    i_0_i_i_c_din = tmp_fu_589_p1.read();
}

void Loop_0_proc19::thread_i_0_i_i_c_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, imatrix_offset_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, omatrix_offset_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, i_0_i_i_c_full_n.read())))) {
        i_0_i_i_c_write = ap_const_logic_1;
    } else {
        i_0_i_i_c_write = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_imatrix_offset_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        imatrix_offset_out_blk_n = imatrix_offset_out_full_n.read();
    } else {
        imatrix_offset_out_blk_n = ap_const_logic_1;
    }
}

void Loop_0_proc19::thread_imatrix_offset_out_din() {
    imatrix_offset_out_din = imatrix_offset.read();
}

void Loop_0_proc19::thread_imatrix_offset_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, imatrix_offset_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, omatrix_offset_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, i_0_i_i_c_full_n.read())))) {
        imatrix_offset_out_write = ap_const_logic_1;
    } else {
        imatrix_offset_out_write = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_in1_buf_0_address0() {
    in1_buf_0_address0 =  (sc_lv<1>) (newIndex1_i_i_i_i_i_fu_908_p1.read());
}

void Loop_0_proc19::thread_in1_buf_0_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        in1_buf_0_ce0 = ap_const_logic_1;
    } else {
        in1_buf_0_ce0 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_in1_buf_0_d0() {
    in1_buf_0_d0 = zigzag_index_q0.read();
}

void Loop_0_proc19::thread_in1_buf_0_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        in1_buf_0_we0 = ap_const_logic_1;
    } else {
        in1_buf_0_we0 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_in1_buf_10_address0() {
    in1_buf_10_address0 =  (sc_lv<1>) (newIndex1_i_i_i_i_i_fu_908_p1.read());
}

void Loop_0_proc19::thread_in1_buf_10_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        in1_buf_10_ce0 = ap_const_logic_1;
    } else {
        in1_buf_10_ce0 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_in1_buf_10_d0() {
    in1_buf_10_d0 = zigzag_index_q10.read();
}

void Loop_0_proc19::thread_in1_buf_10_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        in1_buf_10_we0 = ap_const_logic_1;
    } else {
        in1_buf_10_we0 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_in1_buf_11_address0() {
    in1_buf_11_address0 =  (sc_lv<1>) (newIndex1_i_i_i_i_i_fu_908_p1.read());
}

void Loop_0_proc19::thread_in1_buf_11_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        in1_buf_11_ce0 = ap_const_logic_1;
    } else {
        in1_buf_11_ce0 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_in1_buf_11_d0() {
    in1_buf_11_d0 = zigzag_index_q11.read();
}

void Loop_0_proc19::thread_in1_buf_11_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        in1_buf_11_we0 = ap_const_logic_1;
    } else {
        in1_buf_11_we0 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_in1_buf_12_address0() {
    in1_buf_12_address0 =  (sc_lv<1>) (newIndex1_i_i_i_i_i_fu_908_p1.read());
}

void Loop_0_proc19::thread_in1_buf_12_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        in1_buf_12_ce0 = ap_const_logic_1;
    } else {
        in1_buf_12_ce0 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_in1_buf_12_d0() {
    in1_buf_12_d0 = zigzag_index_q12.read();
}

void Loop_0_proc19::thread_in1_buf_12_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        in1_buf_12_we0 = ap_const_logic_1;
    } else {
        in1_buf_12_we0 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_in1_buf_13_address0() {
    in1_buf_13_address0 =  (sc_lv<1>) (newIndex1_i_i_i_i_i_fu_908_p1.read());
}

void Loop_0_proc19::thread_in1_buf_13_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        in1_buf_13_ce0 = ap_const_logic_1;
    } else {
        in1_buf_13_ce0 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_in1_buf_13_d0() {
    in1_buf_13_d0 = zigzag_index_q13.read();
}

void Loop_0_proc19::thread_in1_buf_13_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        in1_buf_13_we0 = ap_const_logic_1;
    } else {
        in1_buf_13_we0 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_in1_buf_14_address0() {
    in1_buf_14_address0 =  (sc_lv<1>) (newIndex1_i_i_i_i_i_fu_908_p1.read());
}

void Loop_0_proc19::thread_in1_buf_14_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        in1_buf_14_ce0 = ap_const_logic_1;
    } else {
        in1_buf_14_ce0 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_in1_buf_14_d0() {
    in1_buf_14_d0 = zigzag_index_q14.read();
}

void Loop_0_proc19::thread_in1_buf_14_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        in1_buf_14_we0 = ap_const_logic_1;
    } else {
        in1_buf_14_we0 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_in1_buf_15_address0() {
    in1_buf_15_address0 =  (sc_lv<1>) (newIndex1_i_i_i_i_i_fu_908_p1.read());
}

void Loop_0_proc19::thread_in1_buf_15_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        in1_buf_15_ce0 = ap_const_logic_1;
    } else {
        in1_buf_15_ce0 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_in1_buf_15_d0() {
    in1_buf_15_d0 = zigzag_index_q15.read();
}

void Loop_0_proc19::thread_in1_buf_15_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        in1_buf_15_we0 = ap_const_logic_1;
    } else {
        in1_buf_15_we0 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_in1_buf_1_address0() {
    in1_buf_1_address0 =  (sc_lv<1>) (newIndex1_i_i_i_i_i_fu_908_p1.read());
}

void Loop_0_proc19::thread_in1_buf_1_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        in1_buf_1_ce0 = ap_const_logic_1;
    } else {
        in1_buf_1_ce0 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_in1_buf_1_d0() {
    in1_buf_1_d0 = zigzag_index_q1.read();
}

void Loop_0_proc19::thread_in1_buf_1_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        in1_buf_1_we0 = ap_const_logic_1;
    } else {
        in1_buf_1_we0 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_in1_buf_2_address0() {
    in1_buf_2_address0 =  (sc_lv<1>) (newIndex1_i_i_i_i_i_fu_908_p1.read());
}

void Loop_0_proc19::thread_in1_buf_2_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        in1_buf_2_ce0 = ap_const_logic_1;
    } else {
        in1_buf_2_ce0 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_in1_buf_2_d0() {
    in1_buf_2_d0 = zigzag_index_q2.read();
}

void Loop_0_proc19::thread_in1_buf_2_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        in1_buf_2_we0 = ap_const_logic_1;
    } else {
        in1_buf_2_we0 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_in1_buf_3_address0() {
    in1_buf_3_address0 =  (sc_lv<1>) (newIndex1_i_i_i_i_i_fu_908_p1.read());
}

void Loop_0_proc19::thread_in1_buf_3_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        in1_buf_3_ce0 = ap_const_logic_1;
    } else {
        in1_buf_3_ce0 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_in1_buf_3_d0() {
    in1_buf_3_d0 = zigzag_index_q3.read();
}

void Loop_0_proc19::thread_in1_buf_3_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        in1_buf_3_we0 = ap_const_logic_1;
    } else {
        in1_buf_3_we0 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_in1_buf_4_address0() {
    in1_buf_4_address0 =  (sc_lv<1>) (newIndex1_i_i_i_i_i_fu_908_p1.read());
}

void Loop_0_proc19::thread_in1_buf_4_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        in1_buf_4_ce0 = ap_const_logic_1;
    } else {
        in1_buf_4_ce0 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_in1_buf_4_d0() {
    in1_buf_4_d0 = zigzag_index_q4.read();
}

void Loop_0_proc19::thread_in1_buf_4_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        in1_buf_4_we0 = ap_const_logic_1;
    } else {
        in1_buf_4_we0 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_in1_buf_5_address0() {
    in1_buf_5_address0 =  (sc_lv<1>) (newIndex1_i_i_i_i_i_fu_908_p1.read());
}

void Loop_0_proc19::thread_in1_buf_5_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        in1_buf_5_ce0 = ap_const_logic_1;
    } else {
        in1_buf_5_ce0 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_in1_buf_5_d0() {
    in1_buf_5_d0 = zigzag_index_q5.read();
}

void Loop_0_proc19::thread_in1_buf_5_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        in1_buf_5_we0 = ap_const_logic_1;
    } else {
        in1_buf_5_we0 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_in1_buf_6_address0() {
    in1_buf_6_address0 =  (sc_lv<1>) (newIndex1_i_i_i_i_i_fu_908_p1.read());
}

void Loop_0_proc19::thread_in1_buf_6_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        in1_buf_6_ce0 = ap_const_logic_1;
    } else {
        in1_buf_6_ce0 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_in1_buf_6_d0() {
    in1_buf_6_d0 = zigzag_index_q6.read();
}

void Loop_0_proc19::thread_in1_buf_6_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        in1_buf_6_we0 = ap_const_logic_1;
    } else {
        in1_buf_6_we0 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_in1_buf_7_address0() {
    in1_buf_7_address0 =  (sc_lv<1>) (newIndex1_i_i_i_i_i_fu_908_p1.read());
}

void Loop_0_proc19::thread_in1_buf_7_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        in1_buf_7_ce0 = ap_const_logic_1;
    } else {
        in1_buf_7_ce0 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_in1_buf_7_d0() {
    in1_buf_7_d0 = zigzag_index_q7.read();
}

void Loop_0_proc19::thread_in1_buf_7_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        in1_buf_7_we0 = ap_const_logic_1;
    } else {
        in1_buf_7_we0 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_in1_buf_8_address0() {
    in1_buf_8_address0 =  (sc_lv<1>) (newIndex1_i_i_i_i_i_fu_908_p1.read());
}

void Loop_0_proc19::thread_in1_buf_8_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        in1_buf_8_ce0 = ap_const_logic_1;
    } else {
        in1_buf_8_ce0 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_in1_buf_8_d0() {
    in1_buf_8_d0 = zigzag_index_q8.read();
}

void Loop_0_proc19::thread_in1_buf_8_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        in1_buf_8_we0 = ap_const_logic_1;
    } else {
        in1_buf_8_we0 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_in1_buf_9_address0() {
    in1_buf_9_address0 =  (sc_lv<1>) (newIndex1_i_i_i_i_i_fu_908_p1.read());
}

void Loop_0_proc19::thread_in1_buf_9_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        in1_buf_9_ce0 = ap_const_logic_1;
    } else {
        in1_buf_9_ce0 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_in1_buf_9_d0() {
    in1_buf_9_d0 = zigzag_index_q9.read();
}

void Loop_0_proc19::thread_in1_buf_9_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        in1_buf_9_we0 = ap_const_logic_1;
    } else {
        in1_buf_9_we0 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_j_i_15_i_i_i_i_i_fu_902_p2() {
    j_i_15_i_i_i_i_i_fu_902_p2 = (!ap_const_lv6_10.is_01() || !j_0_i_i_i_i_i_i_i_reg_578.read().is_01())? sc_lv<6>(): (sc_biguint<6>(ap_const_lv6_10) + sc_biguint<6>(j_0_i_i_i_i_i_i_i_reg_578.read()));
}

void Loop_0_proc19::thread_newIndex1_i_i_i_i_i_fu_908_p1() {
    newIndex1_i_i_i_i_i_fu_908_p1 = esl_zext<64,2>(newIndex_i_i_i_i_i_reg_959.read());
}

void Loop_0_proc19::thread_offset_i_10_i_i_i_i_s_fu_818_p3() {
    offset_i_10_i_i_i_i_s_fu_818_p3 = esl_concat<1,5>(tmp_reg_927.read(), tmp_i_i_i_21_fu_812_p2.read());
}

void Loop_0_proc19::thread_offset_i_11_i_i_i_i_s_fu_836_p3() {
    offset_i_11_i_i_i_i_s_fu_836_p3 = esl_concat<1,5>(tmp_reg_927.read(), tmp_10_i_i_i_fu_830_p2.read());
}

void Loop_0_proc19::thread_offset_i_12_i_i_i_i_s_fu_854_p3() {
    offset_i_12_i_i_i_i_s_fu_854_p3 = esl_concat<1,5>(tmp_reg_927.read(), tmp_11_i_i_i_fu_848_p2.read());
}

void Loop_0_proc19::thread_offset_i_13_i_i_i_i_s_fu_872_p3() {
    offset_i_13_i_i_i_i_s_fu_872_p3 = esl_concat<1,5>(tmp_reg_927.read(), tmp_12_i_i_i_fu_866_p2.read());
}

void Loop_0_proc19::thread_offset_i_14_i_i_i_i_s_fu_890_p3() {
    offset_i_14_i_i_i_i_s_fu_890_p3 = esl_concat<1,5>(tmp_reg_927.read(), tmp_13_i_i_i_fu_884_p2.read());
}

void Loop_0_proc19::thread_offset_i_1_i_i_i_i_i_fu_638_p3() {
    offset_i_1_i_i_i_i_i_fu_638_p3 = esl_concat<1,5>(tmp_reg_927.read(), tmp_i_i_i_fu_632_p2.read());
}

void Loop_0_proc19::thread_offset_i_2_i_i_i_i_i_fu_656_p3() {
    offset_i_2_i_i_i_i_i_fu_656_p3 = esl_concat<1,5>(tmp_reg_927.read(), tmp_1_i_i_i_fu_650_p2.read());
}

void Loop_0_proc19::thread_offset_i_3_i_i_i_i_i_fu_674_p3() {
    offset_i_3_i_i_i_i_i_fu_674_p3 = esl_concat<1,5>(tmp_reg_927.read(), tmp_2_i_i_i_fu_668_p2.read());
}

void Loop_0_proc19::thread_offset_i_4_i_i_i_i_i_fu_692_p3() {
    offset_i_4_i_i_i_i_i_fu_692_p3 = esl_concat<1,5>(tmp_reg_927.read(), tmp_3_i_i_i_fu_686_p2.read());
}

void Loop_0_proc19::thread_offset_i_5_i_i_i_i_i_fu_710_p3() {
    offset_i_5_i_i_i_i_i_fu_710_p3 = esl_concat<1,5>(tmp_reg_927.read(), tmp_4_i_i_i_fu_704_p2.read());
}

void Loop_0_proc19::thread_offset_i_6_i_i_i_i_i_fu_728_p3() {
    offset_i_6_i_i_i_i_i_fu_728_p3 = esl_concat<1,5>(tmp_reg_927.read(), tmp_5_i_i_i_fu_722_p2.read());
}

void Loop_0_proc19::thread_offset_i_7_i_i_i_i_i_fu_746_p3() {
    offset_i_7_i_i_i_i_i_fu_746_p3 = esl_concat<1,5>(tmp_reg_927.read(), tmp_6_i_i_i_fu_740_p2.read());
}

void Loop_0_proc19::thread_offset_i_8_i_i_i_i_i_fu_764_p3() {
    offset_i_8_i_i_i_i_i_fu_764_p3 = esl_concat<1,5>(tmp_reg_927.read(), tmp_7_i_i_i_fu_758_p2.read());
}

void Loop_0_proc19::thread_offset_i_9_i_i_i_i_i_fu_782_p3() {
    offset_i_9_i_i_i_i_i_fu_782_p3 = esl_concat<1,5>(tmp_reg_927.read(), tmp_8_i_i_i_fu_776_p2.read());
}

void Loop_0_proc19::thread_offset_i_i_i_i_fu_594_p3() {
    offset_i_i_i_i_fu_594_p3 = esl_concat<1,5>(tmp_fu_589_p1.read(), ap_const_lv5_0);
}

void Loop_0_proc19::thread_offset_i_i_i_i_i_i_19_fu_800_p3() {
    offset_i_i_i_i_i_i_19_fu_800_p3 = esl_concat<1,5>(tmp_reg_927.read(), tmp_9_i_i_i_fu_794_p2.read());
}

void Loop_0_proc19::thread_offset_i_i_i_i_i_i_fu_608_p2() {
    offset_i_i_i_i_i_i_fu_608_p2 = (!j_0_i_i_i_i_i_i_i_reg_578.read().is_01() || !offset_i_i_i_i_reg_946.read().is_01())? sc_lv<6>(): (sc_biguint<6>(j_0_i_i_i_i_i_i_i_reg_578.read()) + sc_biguint<6>(offset_i_i_i_i_reg_946.read()));
}

void Loop_0_proc19::thread_omatrix_offset_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        omatrix_offset_out_blk_n = omatrix_offset_out_full_n.read();
    } else {
        omatrix_offset_out_blk_n = ap_const_logic_1;
    }
}

void Loop_0_proc19::thread_omatrix_offset_out_din() {
    omatrix_offset_out_din = omatrix_offset.read();
}

void Loop_0_proc19::thread_omatrix_offset_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, imatrix_offset_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, omatrix_offset_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, i_0_i_i_c_full_n.read())))) {
        omatrix_offset_out_write = ap_const_logic_1;
    } else {
        omatrix_offset_out_write = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_tmp_10_i_i_i_fu_830_p2() {
    tmp_10_i_i_i_fu_830_p2 = (tmp_1_fu_628_p1.read() | ap_const_lv5_C);
}

void Loop_0_proc19::thread_tmp_11_i_i_i_fu_848_p2() {
    tmp_11_i_i_i_fu_848_p2 = (tmp_1_fu_628_p1.read() | ap_const_lv5_D);
}

void Loop_0_proc19::thread_tmp_12_i_i_i_fu_866_p2() {
    tmp_12_i_i_i_fu_866_p2 = (tmp_1_fu_628_p1.read() | ap_const_lv5_E);
}

void Loop_0_proc19::thread_tmp_13_i_i_i_fu_884_p2() {
    tmp_13_i_i_i_fu_884_p2 = (tmp_1_fu_628_p1.read() | ap_const_lv5_F);
}

void Loop_0_proc19::thread_tmp_1_fu_628_p1() {
    tmp_1_fu_628_p1 = j_0_i_i_i_i_i_i_i_reg_578.read().range(5-1, 0);
}

void Loop_0_proc19::thread_tmp_1_i_10_i_i_i_i_i_fu_825_p1() {
    tmp_1_i_10_i_i_i_i_i_fu_825_p1 = esl_zext<64,6>(offset_i_10_i_i_i_i_s_fu_818_p3.read());
}

void Loop_0_proc19::thread_tmp_1_i_11_i_i_i_i_i_fu_843_p1() {
    tmp_1_i_11_i_i_i_i_i_fu_843_p1 = esl_zext<64,6>(offset_i_11_i_i_i_i_s_fu_836_p3.read());
}

void Loop_0_proc19::thread_tmp_1_i_12_i_i_i_i_i_fu_861_p1() {
    tmp_1_i_12_i_i_i_i_i_fu_861_p1 = esl_zext<64,6>(offset_i_12_i_i_i_i_s_fu_854_p3.read());
}

void Loop_0_proc19::thread_tmp_1_i_13_i_i_i_i_i_fu_879_p1() {
    tmp_1_i_13_i_i_i_i_i_fu_879_p1 = esl_zext<64,6>(offset_i_13_i_i_i_i_s_fu_872_p3.read());
}

void Loop_0_proc19::thread_tmp_1_i_14_i_i_i_i_i_fu_897_p1() {
    tmp_1_i_14_i_i_i_i_i_fu_897_p1 = esl_zext<64,6>(offset_i_14_i_i_i_i_s_fu_890_p3.read());
}

void Loop_0_proc19::thread_tmp_1_i_1_i_i_i_i_i_fu_645_p1() {
    tmp_1_i_1_i_i_i_i_i_fu_645_p1 = esl_zext<64,6>(offset_i_1_i_i_i_i_i_fu_638_p3.read());
}

void Loop_0_proc19::thread_tmp_1_i_2_i_i_i_i_i_fu_663_p1() {
    tmp_1_i_2_i_i_i_i_i_fu_663_p1 = esl_zext<64,6>(offset_i_2_i_i_i_i_i_fu_656_p3.read());
}

void Loop_0_proc19::thread_tmp_1_i_3_i_i_i_i_i_fu_681_p1() {
    tmp_1_i_3_i_i_i_i_i_fu_681_p1 = esl_zext<64,6>(offset_i_3_i_i_i_i_i_fu_674_p3.read());
}

void Loop_0_proc19::thread_tmp_1_i_4_i_i_i_i_i_fu_699_p1() {
    tmp_1_i_4_i_i_i_i_i_fu_699_p1 = esl_zext<64,6>(offset_i_4_i_i_i_i_i_fu_692_p3.read());
}

void Loop_0_proc19::thread_tmp_1_i_5_i_i_i_i_i_fu_717_p1() {
    tmp_1_i_5_i_i_i_i_i_fu_717_p1 = esl_zext<64,6>(offset_i_5_i_i_i_i_i_fu_710_p3.read());
}

void Loop_0_proc19::thread_tmp_1_i_6_i_i_i_i_i_fu_735_p1() {
    tmp_1_i_6_i_i_i_i_i_fu_735_p1 = esl_zext<64,6>(offset_i_6_i_i_i_i_i_fu_728_p3.read());
}

void Loop_0_proc19::thread_tmp_1_i_7_i_i_i_i_i_fu_753_p1() {
    tmp_1_i_7_i_i_i_i_i_fu_753_p1 = esl_zext<64,6>(offset_i_7_i_i_i_i_i_fu_746_p3.read());
}

void Loop_0_proc19::thread_tmp_1_i_8_i_i_i_i_i_fu_771_p1() {
    tmp_1_i_8_i_i_i_i_i_fu_771_p1 = esl_zext<64,6>(offset_i_8_i_i_i_i_i_fu_764_p3.read());
}

void Loop_0_proc19::thread_tmp_1_i_9_i_i_i_i_i_fu_789_p1() {
    tmp_1_i_9_i_i_i_i_i_fu_789_p1 = esl_zext<64,6>(offset_i_9_i_i_i_i_i_fu_782_p3.read());
}

void Loop_0_proc19::thread_tmp_1_i_i_i_fu_650_p2() {
    tmp_1_i_i_i_fu_650_p2 = (tmp_1_fu_628_p1.read() | ap_const_lv5_2);
}

void Loop_0_proc19::thread_tmp_1_i_i_i_i_i_i_20_fu_807_p1() {
    tmp_1_i_i_i_i_i_i_20_fu_807_p1 = esl_zext<64,6>(offset_i_i_i_i_i_i_19_fu_800_p3.read());
}

void Loop_0_proc19::thread_tmp_1_i_i_i_i_i_i_fu_613_p1() {
    tmp_1_i_i_i_i_i_i_fu_613_p1 = esl_zext<64,6>(offset_i_i_i_i_i_i_fu_608_p2.read());
}

void Loop_0_proc19::thread_tmp_2_i_i_i_fu_668_p2() {
    tmp_2_i_i_i_fu_668_p2 = (tmp_1_fu_628_p1.read() | ap_const_lv5_3);
}

void Loop_0_proc19::thread_tmp_3_i_i_i_fu_686_p2() {
    tmp_3_i_i_i_fu_686_p2 = (tmp_1_fu_628_p1.read() | ap_const_lv5_4);
}

void Loop_0_proc19::thread_tmp_4_i_i_i_fu_704_p2() {
    tmp_4_i_i_i_fu_704_p2 = (tmp_1_fu_628_p1.read() | ap_const_lv5_5);
}

void Loop_0_proc19::thread_tmp_5_i_i_i_fu_722_p2() {
    tmp_5_i_i_i_fu_722_p2 = (tmp_1_fu_628_p1.read() | ap_const_lv5_6);
}

void Loop_0_proc19::thread_tmp_6_i_i_i_fu_740_p2() {
    tmp_6_i_i_i_fu_740_p2 = (tmp_1_fu_628_p1.read() | ap_const_lv5_7);
}

void Loop_0_proc19::thread_tmp_7_i_i_i_fu_758_p2() {
    tmp_7_i_i_i_fu_758_p2 = (tmp_1_fu_628_p1.read() | ap_const_lv5_8);
}

void Loop_0_proc19::thread_tmp_8_i_i_i_fu_776_p2() {
    tmp_8_i_i_i_fu_776_p2 = (tmp_1_fu_628_p1.read() | ap_const_lv5_9);
}

void Loop_0_proc19::thread_tmp_9_i_i_i_fu_794_p2() {
    tmp_9_i_i_i_fu_794_p2 = (tmp_1_fu_628_p1.read() | ap_const_lv5_A);
}

void Loop_0_proc19::thread_tmp_fu_589_p1() {
    tmp_fu_589_p1 = i_0_i_i.read().range(1-1, 0);
}

void Loop_0_proc19::thread_tmp_i_i_i_21_fu_812_p2() {
    tmp_i_i_i_21_fu_812_p2 = (tmp_1_fu_628_p1.read() | ap_const_lv5_B);
}

void Loop_0_proc19::thread_tmp_i_i_i_fu_632_p2() {
    tmp_i_i_i_fu_632_p2 = (tmp_1_fu_628_p1.read() | ap_const_lv5_1);
}

void Loop_0_proc19::thread_zigzag_index_address0() {
    zigzag_index_address0 =  (sc_lv<6>) (tmp_1_i_i_i_i_i_i_fu_613_p1.read());
}

void Loop_0_proc19::thread_zigzag_index_address1() {
    zigzag_index_address1 =  (sc_lv<6>) (tmp_1_i_1_i_i_i_i_i_fu_645_p1.read());
}

void Loop_0_proc19::thread_zigzag_index_address10() {
    zigzag_index_address10 =  (sc_lv<6>) (tmp_1_i_i_i_i_i_i_20_fu_807_p1.read());
}

void Loop_0_proc19::thread_zigzag_index_address11() {
    zigzag_index_address11 =  (sc_lv<6>) (tmp_1_i_10_i_i_i_i_i_fu_825_p1.read());
}

void Loop_0_proc19::thread_zigzag_index_address12() {
    zigzag_index_address12 =  (sc_lv<6>) (tmp_1_i_11_i_i_i_i_i_fu_843_p1.read());
}

void Loop_0_proc19::thread_zigzag_index_address13() {
    zigzag_index_address13 =  (sc_lv<6>) (tmp_1_i_12_i_i_i_i_i_fu_861_p1.read());
}

void Loop_0_proc19::thread_zigzag_index_address14() {
    zigzag_index_address14 =  (sc_lv<6>) (tmp_1_i_13_i_i_i_i_i_fu_879_p1.read());
}

void Loop_0_proc19::thread_zigzag_index_address15() {
    zigzag_index_address15 =  (sc_lv<6>) (tmp_1_i_14_i_i_i_i_i_fu_897_p1.read());
}

void Loop_0_proc19::thread_zigzag_index_address2() {
    zigzag_index_address2 =  (sc_lv<6>) (tmp_1_i_2_i_i_i_i_i_fu_663_p1.read());
}

void Loop_0_proc19::thread_zigzag_index_address3() {
    zigzag_index_address3 =  (sc_lv<6>) (tmp_1_i_3_i_i_i_i_i_fu_681_p1.read());
}

void Loop_0_proc19::thread_zigzag_index_address4() {
    zigzag_index_address4 =  (sc_lv<6>) (tmp_1_i_4_i_i_i_i_i_fu_699_p1.read());
}

void Loop_0_proc19::thread_zigzag_index_address5() {
    zigzag_index_address5 =  (sc_lv<6>) (tmp_1_i_5_i_i_i_i_i_fu_717_p1.read());
}

void Loop_0_proc19::thread_zigzag_index_address6() {
    zigzag_index_address6 =  (sc_lv<6>) (tmp_1_i_6_i_i_i_i_i_fu_735_p1.read());
}

void Loop_0_proc19::thread_zigzag_index_address7() {
    zigzag_index_address7 =  (sc_lv<6>) (tmp_1_i_7_i_i_i_i_i_fu_753_p1.read());
}

void Loop_0_proc19::thread_zigzag_index_address8() {
    zigzag_index_address8 =  (sc_lv<6>) (tmp_1_i_8_i_i_i_i_i_fu_771_p1.read());
}

void Loop_0_proc19::thread_zigzag_index_address9() {
    zigzag_index_address9 =  (sc_lv<6>) (tmp_1_i_9_i_i_i_i_i_fu_789_p1.read());
}

void Loop_0_proc19::thread_zigzag_index_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        zigzag_index_ce0 = ap_const_logic_1;
    } else {
        zigzag_index_ce0 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_zigzag_index_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        zigzag_index_ce1 = ap_const_logic_1;
    } else {
        zigzag_index_ce1 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_zigzag_index_ce10() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        zigzag_index_ce10 = ap_const_logic_1;
    } else {
        zigzag_index_ce10 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_zigzag_index_ce11() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        zigzag_index_ce11 = ap_const_logic_1;
    } else {
        zigzag_index_ce11 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_zigzag_index_ce12() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        zigzag_index_ce12 = ap_const_logic_1;
    } else {
        zigzag_index_ce12 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_zigzag_index_ce13() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        zigzag_index_ce13 = ap_const_logic_1;
    } else {
        zigzag_index_ce13 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_zigzag_index_ce14() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        zigzag_index_ce14 = ap_const_logic_1;
    } else {
        zigzag_index_ce14 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_zigzag_index_ce15() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        zigzag_index_ce15 = ap_const_logic_1;
    } else {
        zigzag_index_ce15 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_zigzag_index_ce2() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        zigzag_index_ce2 = ap_const_logic_1;
    } else {
        zigzag_index_ce2 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_zigzag_index_ce3() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        zigzag_index_ce3 = ap_const_logic_1;
    } else {
        zigzag_index_ce3 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_zigzag_index_ce4() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        zigzag_index_ce4 = ap_const_logic_1;
    } else {
        zigzag_index_ce4 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_zigzag_index_ce5() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        zigzag_index_ce5 = ap_const_logic_1;
    } else {
        zigzag_index_ce5 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_zigzag_index_ce6() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        zigzag_index_ce6 = ap_const_logic_1;
    } else {
        zigzag_index_ce6 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_zigzag_index_ce7() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        zigzag_index_ce7 = ap_const_logic_1;
    } else {
        zigzag_index_ce7 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_zigzag_index_ce8() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        zigzag_index_ce8 = ap_const_logic_1;
    } else {
        zigzag_index_ce8 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_zigzag_index_ce9() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        zigzag_index_ce9 = ap_const_logic_1;
    } else {
        zigzag_index_ce9 = ap_const_logic_0;
    }
}

void Loop_0_proc19::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, imatrix_offset_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, omatrix_offset_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, i_0_i_i_c_full_n.read())))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond1_i_i_i_i_i_s_fu_602_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

}

