// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xdecode_start_f2r_vectorph_s2e_forbody96preheader.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XDecode_start_f2r_vectorph_s2e_forbody96preheader_CfgInitialize(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr, XDecode_start_f2r_vectorph_s2e_forbody96preheader_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Bus_ctrl_BaseAddress = ConfigPtr->Bus_ctrl_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XDecode_start_f2r_vectorph_s2e_forbody96preheader_Start(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDecode_start_f2r_vectorph_s2e_forbody96preheader_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XDECODE_START_F2R_VECTORPH_S2E_FORBODY96PREHEADER_BUS_CTRL_ADDR_AP_CTRL) & 0x80;
    XDecode_start_f2r_vectorph_s2e_forbody96preheader_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XDECODE_START_F2R_VECTORPH_S2E_FORBODY96PREHEADER_BUS_CTRL_ADDR_AP_CTRL, Data | 0x01);
}

u32 XDecode_start_f2r_vectorph_s2e_forbody96preheader_IsDone(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDecode_start_f2r_vectorph_s2e_forbody96preheader_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XDECODE_START_F2R_VECTORPH_S2E_FORBODY96PREHEADER_BUS_CTRL_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XDecode_start_f2r_vectorph_s2e_forbody96preheader_IsIdle(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDecode_start_f2r_vectorph_s2e_forbody96preheader_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XDECODE_START_F2R_VECTORPH_S2E_FORBODY96PREHEADER_BUS_CTRL_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XDecode_start_f2r_vectorph_s2e_forbody96preheader_IsReady(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDecode_start_f2r_vectorph_s2e_forbody96preheader_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XDECODE_START_F2R_VECTORPH_S2E_FORBODY96PREHEADER_BUS_CTRL_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XDecode_start_f2r_vectorph_s2e_forbody96preheader_EnableAutoRestart(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDecode_start_f2r_vectorph_s2e_forbody96preheader_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XDECODE_START_F2R_VECTORPH_S2E_FORBODY96PREHEADER_BUS_CTRL_ADDR_AP_CTRL, 0x80);
}

void XDecode_start_f2r_vectorph_s2e_forbody96preheader_DisableAutoRestart(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDecode_start_f2r_vectorph_s2e_forbody96preheader_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XDECODE_START_F2R_VECTORPH_S2E_FORBODY96PREHEADER_BUS_CTRL_ADDR_AP_CTRL, 0);
}

void XDecode_start_f2r_vectorph_s2e_forbody96preheader_Set_y_buf(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr, u64 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDecode_start_f2r_vectorph_s2e_forbody96preheader_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XDECODE_START_F2R_VECTORPH_S2E_FORBODY96PREHEADER_BUS_CTRL_ADDR_Y_BUF_DATA, (u32)(Data));
    XDecode_start_f2r_vectorph_s2e_forbody96preheader_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XDECODE_START_F2R_VECTORPH_S2E_FORBODY96PREHEADER_BUS_CTRL_ADDR_Y_BUF_DATA + 4, (u32)(Data >> 32));
}

u64 XDecode_start_f2r_vectorph_s2e_forbody96preheader_Get_y_buf(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr) {
    u64 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDecode_start_f2r_vectorph_s2e_forbody96preheader_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XDECODE_START_F2R_VECTORPH_S2E_FORBODY96PREHEADER_BUS_CTRL_ADDR_Y_BUF_DATA);
    Data += (u64)XDecode_start_f2r_vectorph_s2e_forbody96preheader_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XDECODE_START_F2R_VECTORPH_S2E_FORBODY96PREHEADER_BUS_CTRL_ADDR_Y_BUF_DATA + 4) << 32;
    return Data;
}

void XDecode_start_f2r_vectorph_s2e_forbody96preheader_Set_u_buf(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr, u64 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDecode_start_f2r_vectorph_s2e_forbody96preheader_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XDECODE_START_F2R_VECTORPH_S2E_FORBODY96PREHEADER_BUS_CTRL_ADDR_U_BUF_DATA, (u32)(Data));
    XDecode_start_f2r_vectorph_s2e_forbody96preheader_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XDECODE_START_F2R_VECTORPH_S2E_FORBODY96PREHEADER_BUS_CTRL_ADDR_U_BUF_DATA + 4, (u32)(Data >> 32));
}

u64 XDecode_start_f2r_vectorph_s2e_forbody96preheader_Get_u_buf(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr) {
    u64 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDecode_start_f2r_vectorph_s2e_forbody96preheader_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XDECODE_START_F2R_VECTORPH_S2E_FORBODY96PREHEADER_BUS_CTRL_ADDR_U_BUF_DATA);
    Data += (u64)XDecode_start_f2r_vectorph_s2e_forbody96preheader_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XDECODE_START_F2R_VECTORPH_S2E_FORBODY96PREHEADER_BUS_CTRL_ADDR_U_BUF_DATA + 4) << 32;
    return Data;
}

void XDecode_start_f2r_vectorph_s2e_forbody96preheader_Set_v_buf(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr, u64 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDecode_start_f2r_vectorph_s2e_forbody96preheader_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XDECODE_START_F2R_VECTORPH_S2E_FORBODY96PREHEADER_BUS_CTRL_ADDR_V_BUF_DATA, (u32)(Data));
    XDecode_start_f2r_vectorph_s2e_forbody96preheader_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XDECODE_START_F2R_VECTORPH_S2E_FORBODY96PREHEADER_BUS_CTRL_ADDR_V_BUF_DATA + 4, (u32)(Data >> 32));
}

u64 XDecode_start_f2r_vectorph_s2e_forbody96preheader_Get_v_buf(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr) {
    u64 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDecode_start_f2r_vectorph_s2e_forbody96preheader_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XDECODE_START_F2R_VECTORPH_S2E_FORBODY96PREHEADER_BUS_CTRL_ADDR_V_BUF_DATA);
    Data += (u64)XDecode_start_f2r_vectorph_s2e_forbody96preheader_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XDECODE_START_F2R_VECTORPH_S2E_FORBODY96PREHEADER_BUS_CTRL_ADDR_V_BUF_DATA + 4) << 32;
    return Data;
}

void XDecode_start_f2r_vectorph_s2e_forbody96preheader_Set_rgb_buf(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr, u64 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDecode_start_f2r_vectorph_s2e_forbody96preheader_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XDECODE_START_F2R_VECTORPH_S2E_FORBODY96PREHEADER_BUS_CTRL_ADDR_RGB_BUF_DATA, (u32)(Data));
    XDecode_start_f2r_vectorph_s2e_forbody96preheader_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XDECODE_START_F2R_VECTORPH_S2E_FORBODY96PREHEADER_BUS_CTRL_ADDR_RGB_BUF_DATA + 4, (u32)(Data >> 32));
}

u64 XDecode_start_f2r_vectorph_s2e_forbody96preheader_Get_rgb_buf(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr) {
    u64 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDecode_start_f2r_vectorph_s2e_forbody96preheader_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XDECODE_START_F2R_VECTORPH_S2E_FORBODY96PREHEADER_BUS_CTRL_ADDR_RGB_BUF_DATA);
    Data += (u64)XDecode_start_f2r_vectorph_s2e_forbody96preheader_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XDECODE_START_F2R_VECTORPH_S2E_FORBODY96PREHEADER_BUS_CTRL_ADDR_RGB_BUF_DATA + 4) << 32;
    return Data;
}

void XDecode_start_f2r_vectorph_s2e_forbody96preheader_InterruptGlobalEnable(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDecode_start_f2r_vectorph_s2e_forbody96preheader_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XDECODE_START_F2R_VECTORPH_S2E_FORBODY96PREHEADER_BUS_CTRL_ADDR_GIE, 1);
}

void XDecode_start_f2r_vectorph_s2e_forbody96preheader_InterruptGlobalDisable(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDecode_start_f2r_vectorph_s2e_forbody96preheader_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XDECODE_START_F2R_VECTORPH_S2E_FORBODY96PREHEADER_BUS_CTRL_ADDR_GIE, 0);
}

void XDecode_start_f2r_vectorph_s2e_forbody96preheader_InterruptEnable(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XDecode_start_f2r_vectorph_s2e_forbody96preheader_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XDECODE_START_F2R_VECTORPH_S2E_FORBODY96PREHEADER_BUS_CTRL_ADDR_IER);
    XDecode_start_f2r_vectorph_s2e_forbody96preheader_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XDECODE_START_F2R_VECTORPH_S2E_FORBODY96PREHEADER_BUS_CTRL_ADDR_IER, Register | Mask);
}

void XDecode_start_f2r_vectorph_s2e_forbody96preheader_InterruptDisable(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XDecode_start_f2r_vectorph_s2e_forbody96preheader_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XDECODE_START_F2R_VECTORPH_S2E_FORBODY96PREHEADER_BUS_CTRL_ADDR_IER);
    XDecode_start_f2r_vectorph_s2e_forbody96preheader_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XDECODE_START_F2R_VECTORPH_S2E_FORBODY96PREHEADER_BUS_CTRL_ADDR_IER, Register & (~Mask));
}

void XDecode_start_f2r_vectorph_s2e_forbody96preheader_InterruptClear(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDecode_start_f2r_vectorph_s2e_forbody96preheader_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XDECODE_START_F2R_VECTORPH_S2E_FORBODY96PREHEADER_BUS_CTRL_ADDR_ISR, Mask);
}

u32 XDecode_start_f2r_vectorph_s2e_forbody96preheader_InterruptGetEnabled(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XDecode_start_f2r_vectorph_s2e_forbody96preheader_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XDECODE_START_F2R_VECTORPH_S2E_FORBODY96PREHEADER_BUS_CTRL_ADDR_IER);
}

u32 XDecode_start_f2r_vectorph_s2e_forbody96preheader_InterruptGetStatus(XDecode_start_f2r_vectorph_s2e_forbody96preheader *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XDecode_start_f2r_vectorph_s2e_forbody96preheader_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XDECODE_START_F2R_VECTORPH_S2E_FORBODY96PREHEADER_BUS_CTRL_ADDR_ISR);
}

