// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xwriteoneblock_f2r_entry_s2e_forend13.h"

extern XWriteoneblock_f2r_entry_s2e_forend13_Config XWriteoneblock_f2r_entry_s2e_forend13_ConfigTable[];

XWriteoneblock_f2r_entry_s2e_forend13_Config *XWriteoneblock_f2r_entry_s2e_forend13_LookupConfig(u16 DeviceId) {
	XWriteoneblock_f2r_entry_s2e_forend13_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XWRITEONEBLOCK_F2R_ENTRY_S2E_FOREND13_NUM_INSTANCES; Index++) {
		if (XWriteoneblock_f2r_entry_s2e_forend13_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XWriteoneblock_f2r_entry_s2e_forend13_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XWriteoneblock_f2r_entry_s2e_forend13_Initialize(XWriteoneblock_f2r_entry_s2e_forend13 *InstancePtr, u16 DeviceId) {
	XWriteoneblock_f2r_entry_s2e_forend13_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XWriteoneblock_f2r_entry_s2e_forend13_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XWriteoneblock_f2r_entry_s2e_forend13_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

