# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2017.4
# Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
# 
# ==============================================================

proc generate {drv_handle} {
    xdefine_include_file $drv_handle "xparameters.h" "XIzigzagmatrix_f2r_forbody_s2e_forend" \
        "NUM_INSTANCES" \
        "DEVICE_ID" \
        "C_S_AXI_BUS_CTRL_BASEADDR" \
        "C_S_AXI_BUS_CTRL_HIGHADDR"

    xdefine_config_file $drv_handle "xizigzagmatrix_f2r_forbody_s2e_forend_g.c" "XIzigzagmatrix_f2r_forbody_s2e_forend" \
        "DEVICE_ID" \
        "C_S_AXI_BUS_CTRL_BASEADDR"

    xdefine_canonical_xpars $drv_handle "xparameters.h" "XIzigzagmatrix_f2r_forbody_s2e_forend" \
        "DEVICE_ID" \
        "C_S_AXI_BUS_CTRL_BASEADDR" \
        "C_S_AXI_BUS_CTRL_HIGHADDR"
}

