# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/giorgio/workspace/jpeg-rs-clean/sys/jpeg-rs/jpeg-rs.srcs/sources_1/bd/design_1/ip/design_1_WriteOneBlock_f2r_entry_s2e_forEnd13_0_0/design_1_WriteOneBlock_f2r_entry_s2e_forEnd13_0_0.xci
# IP: The module: 'design_1_WriteOneBlock_f2r_entry_s2e_forEnd13_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/giorgio/workspace/jpeg-rs-clean/sys/jpeg-rs/jpeg-rs.srcs/sources_1/bd/design_1/ip/design_1_WriteOneBlock_f2r_entry_s2e_forEnd13_0_0/constraints/WriteOneBlock_f2r_entry_s2e_forEnd13_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_WriteOneBlock_f2r_entry_s2e_forEnd13_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/giorgio/workspace/jpeg-rs-clean/sys/jpeg-rs/jpeg-rs.srcs/sources_1/bd/design_1/ip/design_1_WriteOneBlock_f2r_entry_s2e_forEnd13_0_0/design_1_WriteOneBlock_f2r_entry_s2e_forEnd13_0_0.xci
# IP: The module: 'design_1_WriteOneBlock_f2r_entry_s2e_forEnd13_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/giorgio/workspace/jpeg-rs-clean/sys/jpeg-rs/jpeg-rs.srcs/sources_1/bd/design_1/ip/design_1_WriteOneBlock_f2r_entry_s2e_forEnd13_0_0/constraints/WriteOneBlock_f2r_entry_s2e_forEnd13_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_WriteOneBlock_f2r_entry_s2e_forEnd13_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
