// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xizigzagmatrix_f2r_forbody_s2e_forend.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XIzigzagmatrix_f2r_forbody_s2e_forend_CfgInitialize(XIzigzagmatrix_f2r_forbody_s2e_forend *InstancePtr, XIzigzagmatrix_f2r_forbody_s2e_forend_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Bus_ctrl_BaseAddress = ConfigPtr->Bus_ctrl_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XIzigzagmatrix_f2r_forbody_s2e_forend_Start(XIzigzagmatrix_f2r_forbody_s2e_forend *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XIzigzagmatrix_f2r_forbody_s2e_forend_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XIZIGZAGMATRIX_F2R_FORBODY_S2E_FOREND_BUS_CTRL_ADDR_AP_CTRL) & 0x80;
    XIzigzagmatrix_f2r_forbody_s2e_forend_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XIZIGZAGMATRIX_F2R_FORBODY_S2E_FOREND_BUS_CTRL_ADDR_AP_CTRL, Data | 0x01);
}

u32 XIzigzagmatrix_f2r_forbody_s2e_forend_IsDone(XIzigzagmatrix_f2r_forbody_s2e_forend *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XIzigzagmatrix_f2r_forbody_s2e_forend_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XIZIGZAGMATRIX_F2R_FORBODY_S2E_FOREND_BUS_CTRL_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XIzigzagmatrix_f2r_forbody_s2e_forend_IsIdle(XIzigzagmatrix_f2r_forbody_s2e_forend *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XIzigzagmatrix_f2r_forbody_s2e_forend_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XIZIGZAGMATRIX_F2R_FORBODY_S2E_FOREND_BUS_CTRL_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XIzigzagmatrix_f2r_forbody_s2e_forend_IsReady(XIzigzagmatrix_f2r_forbody_s2e_forend *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XIzigzagmatrix_f2r_forbody_s2e_forend_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XIZIGZAGMATRIX_F2R_FORBODY_S2E_FOREND_BUS_CTRL_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XIzigzagmatrix_f2r_forbody_s2e_forend_EnableAutoRestart(XIzigzagmatrix_f2r_forbody_s2e_forend *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XIzigzagmatrix_f2r_forbody_s2e_forend_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XIZIGZAGMATRIX_F2R_FORBODY_S2E_FOREND_BUS_CTRL_ADDR_AP_CTRL, 0x80);
}

void XIzigzagmatrix_f2r_forbody_s2e_forend_DisableAutoRestart(XIzigzagmatrix_f2r_forbody_s2e_forend *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XIzigzagmatrix_f2r_forbody_s2e_forend_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XIZIGZAGMATRIX_F2R_FORBODY_S2E_FOREND_BUS_CTRL_ADDR_AP_CTRL, 0);
}

void XIzigzagmatrix_f2r_forbody_s2e_forend_Set_imatrix(XIzigzagmatrix_f2r_forbody_s2e_forend *InstancePtr, u64 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XIzigzagmatrix_f2r_forbody_s2e_forend_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XIZIGZAGMATRIX_F2R_FORBODY_S2E_FOREND_BUS_CTRL_ADDR_IMATRIX_DATA, (u32)(Data));
    XIzigzagmatrix_f2r_forbody_s2e_forend_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XIZIGZAGMATRIX_F2R_FORBODY_S2E_FOREND_BUS_CTRL_ADDR_IMATRIX_DATA + 4, (u32)(Data >> 32));
}

u64 XIzigzagmatrix_f2r_forbody_s2e_forend_Get_imatrix(XIzigzagmatrix_f2r_forbody_s2e_forend *InstancePtr) {
    u64 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XIzigzagmatrix_f2r_forbody_s2e_forend_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XIZIGZAGMATRIX_F2R_FORBODY_S2E_FOREND_BUS_CTRL_ADDR_IMATRIX_DATA);
    Data += (u64)XIzigzagmatrix_f2r_forbody_s2e_forend_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XIZIGZAGMATRIX_F2R_FORBODY_S2E_FOREND_BUS_CTRL_ADDR_IMATRIX_DATA + 4) << 32;
    return Data;
}

void XIzigzagmatrix_f2r_forbody_s2e_forend_Set_omatrix(XIzigzagmatrix_f2r_forbody_s2e_forend *InstancePtr, u64 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XIzigzagmatrix_f2r_forbody_s2e_forend_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XIZIGZAGMATRIX_F2R_FORBODY_S2E_FOREND_BUS_CTRL_ADDR_OMATRIX_DATA, (u32)(Data));
    XIzigzagmatrix_f2r_forbody_s2e_forend_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XIZIGZAGMATRIX_F2R_FORBODY_S2E_FOREND_BUS_CTRL_ADDR_OMATRIX_DATA + 4, (u32)(Data >> 32));
}

u64 XIzigzagmatrix_f2r_forbody_s2e_forend_Get_omatrix(XIzigzagmatrix_f2r_forbody_s2e_forend *InstancePtr) {
    u64 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XIzigzagmatrix_f2r_forbody_s2e_forend_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XIZIGZAGMATRIX_F2R_FORBODY_S2E_FOREND_BUS_CTRL_ADDR_OMATRIX_DATA);
    Data += (u64)XIzigzagmatrix_f2r_forbody_s2e_forend_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XIZIGZAGMATRIX_F2R_FORBODY_S2E_FOREND_BUS_CTRL_ADDR_OMATRIX_DATA + 4) << 32;
    return Data;
}

void XIzigzagmatrix_f2r_forbody_s2e_forend_InterruptGlobalEnable(XIzigzagmatrix_f2r_forbody_s2e_forend *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XIzigzagmatrix_f2r_forbody_s2e_forend_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XIZIGZAGMATRIX_F2R_FORBODY_S2E_FOREND_BUS_CTRL_ADDR_GIE, 1);
}

void XIzigzagmatrix_f2r_forbody_s2e_forend_InterruptGlobalDisable(XIzigzagmatrix_f2r_forbody_s2e_forend *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XIzigzagmatrix_f2r_forbody_s2e_forend_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XIZIGZAGMATRIX_F2R_FORBODY_S2E_FOREND_BUS_CTRL_ADDR_GIE, 0);
}

void XIzigzagmatrix_f2r_forbody_s2e_forend_InterruptEnable(XIzigzagmatrix_f2r_forbody_s2e_forend *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XIzigzagmatrix_f2r_forbody_s2e_forend_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XIZIGZAGMATRIX_F2R_FORBODY_S2E_FOREND_BUS_CTRL_ADDR_IER);
    XIzigzagmatrix_f2r_forbody_s2e_forend_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XIZIGZAGMATRIX_F2R_FORBODY_S2E_FOREND_BUS_CTRL_ADDR_IER, Register | Mask);
}

void XIzigzagmatrix_f2r_forbody_s2e_forend_InterruptDisable(XIzigzagmatrix_f2r_forbody_s2e_forend *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XIzigzagmatrix_f2r_forbody_s2e_forend_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XIZIGZAGMATRIX_F2R_FORBODY_S2E_FOREND_BUS_CTRL_ADDR_IER);
    XIzigzagmatrix_f2r_forbody_s2e_forend_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XIZIGZAGMATRIX_F2R_FORBODY_S2E_FOREND_BUS_CTRL_ADDR_IER, Register & (~Mask));
}

void XIzigzagmatrix_f2r_forbody_s2e_forend_InterruptClear(XIzigzagmatrix_f2r_forbody_s2e_forend *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XIzigzagmatrix_f2r_forbody_s2e_forend_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XIZIGZAGMATRIX_F2R_FORBODY_S2E_FOREND_BUS_CTRL_ADDR_ISR, Mask);
}

u32 XIzigzagmatrix_f2r_forbody_s2e_forend_InterruptGetEnabled(XIzigzagmatrix_f2r_forbody_s2e_forend *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XIzigzagmatrix_f2r_forbody_s2e_forend_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XIZIGZAGMATRIX_F2R_FORBODY_S2E_FOREND_BUS_CTRL_ADDR_IER);
}

u32 XIzigzagmatrix_f2r_forbody_s2e_forend_InterruptGetStatus(XIzigzagmatrix_f2r_forbody_s2e_forend *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XIzigzagmatrix_f2r_forbody_s2e_forend_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XIZIGZAGMATRIX_F2R_FORBODY_S2E_FOREND_BUS_CTRL_ADDR_ISR);
}

