// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// ==============================================================

#include <systemc>
#include <iostream>
#include <cstdlib>
#include <cstddef>
#include <stdint.h>
#include "SysCFileHandler.h"
#include "ap_int.h"
#include "ap_fixed.h"
#include <complex>
#include <stdbool.h>
#include "autopilot_cbe.h"
#include "ap_stream.h"
#include "hls_stream.h"
#include "hls_half.h"
#include "hls_signal_handler.h"

using namespace std;
using namespace sc_core;
using namespace sc_dt;


// [dump_struct_tree [build_nameSpaceTree] dumpedStructList] ---------->


// [dump_enumeration [get_enumeration_list]] ---------->


// wrapc file define: "BUS_DST"
#define AUTOTB_TVIN_BUS_DST  "../tv/cdatafile/c.BoundIDctMatrix.autotvin_BUS_DST.dat"
#define AUTOTB_TVOUT_BUS_DST  "../tv/cdatafile/c.BoundIDctMatrix.autotvout_BUS_DST.dat"
// wrapc file define: "matrix"
#define AUTOTB_TVIN_matrix  "../tv/cdatafile/c.BoundIDctMatrix.autotvin_matrix.dat"
// wrapc file define: "Bound"
#define AUTOTB_TVIN_Bound  "../tv/cdatafile/c.BoundIDctMatrix.autotvin_Bound.dat"

#define INTER_TCL  "../tv/cdatafile/ref.tcl"

// tvout file define: "BUS_DST"
#define AUTOTB_TVOUT_PC_BUS_DST  "../tv/rtldatafile/rtl.BoundIDctMatrix.autotvout_BUS_DST.dat"

class INTER_TCL_FILE {
	public:
		INTER_TCL_FILE(const char* name) {
			mName = name;
			BUS_DST_depth = 0;
			matrix_depth = 0;
			Bound_depth = 0;
			trans_num =0;
		}

		~INTER_TCL_FILE() {
			mFile.open(mName);
			if (!mFile.good()) {
				cout << "Failed to open file ref.tcl" << endl;
				exit (1);
			}
			string total_list = get_depth_list();
			mFile << "set depth_list {\n";
			mFile << total_list;
			mFile << "}\n";
			mFile << "set trans_num "<<trans_num<<endl;
			mFile.close();
		}

		string get_depth_list () {
			stringstream total_list;
			total_list << "{BUS_DST " << BUS_DST_depth << "}\n";
			total_list << "{matrix " << matrix_depth << "}\n";
			total_list << "{Bound " << Bound_depth << "}\n";
			return total_list.str();
		}

		void set_num (int num , int* class_num) {
			(*class_num) = (*class_num) > num ? (*class_num) : num;
		}
	public:
		int BUS_DST_depth;
		int matrix_depth;
		int Bound_depth;
		int trans_num;

	private:
		ofstream mFile;
		const char* mName;
};

extern "C" void BoundIDctMatrix (
int matrix[64],
int Bound);

extern "C" void AESL_WRAP_BoundIDctMatrix (
int matrix[64],
int Bound)
{
	refine_signal_handler();
	fstream wrapc_switch_file_token;
	wrapc_switch_file_token.open(".hls_cosim_wrapc_switch.log");
	int AESL_i;
	if (wrapc_switch_file_token.good())
	{
		CodeState = ENTER_WRAPC_PC;
		static unsigned AESL_transaction_pc = 0;
		string AESL_token;
		string AESL_num;
		static AESL_FILE_HANDLER aesl_fh;


		// output port post check: "BUS_DST"
		aesl_fh.read(AUTOTB_TVOUT_PC_BUS_DST, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_BUS_DST, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_BUS_DST, AESL_token); // data

			sc_bv<32> *BUS_DST_pc_buffer = new sc_bv<32>[64];
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'BUS_DST', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'BUS_DST', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					BUS_DST_pc_buffer[i] = AESL_token.c_str();
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_BUS_DST, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_BUS_DST))
				{
					exit(1);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: BUS_DST
				{
					// bitslice(31, 0)
					// {
						// celement: matrix(31, 0)
						// {
							sc_lv<32>* matrix_lv0_0_63_1 = new sc_lv<32>[64];
						// }
					// }

					// bitslice(31, 0)
					{
						int hls_map_index = 0;
						// celement: matrix(31, 0)
						{
							// carray: (0) => (63) @ (1)
							for (int i_0 = 0; i_0 <= 63; i_0 += 1)
							{
								if (&(matrix[0]) != NULL) // check the null address if the c port is array or others
								{
									matrix_lv0_0_63_1[hls_map_index].range(31, 0) = sc_bv<32>(BUS_DST_pc_buffer[hls_map_index].range(31, 0));
									hls_map_index++;
								}
							}
						}
					}

					// bitslice(31, 0)
					{
						int hls_map_index = 0;
						// celement: matrix(31, 0)
						{
							// carray: (0) => (63) @ (1)
							for (int i_0 = 0; i_0 <= 63; i_0 += 1)
							{
								// sub                    : i_0
								// ori_name               : matrix[i_0]
								// sub_1st_elem           : 0
								// ori_name_1st_elem      : matrix[0]
								// output_left_conversion : matrix[i_0]
								// output_type_conversion : (matrix_lv0_0_63_1[hls_map_index]).to_uint64()
								if (&(matrix[0]) != NULL) // check the null address if the c port is array or others
								{
									matrix[i_0] = (matrix_lv0_0_63_1[hls_map_index]).to_uint64();
									hls_map_index++;
								}
							}
						}
					}
				}
			}

			// release memory allocation
			delete [] BUS_DST_pc_buffer;
		}

		AESL_transaction_pc++;
	}
	else
	{
		CodeState = ENTER_WRAPC;
		static unsigned AESL_transaction;

		static AESL_FILE_HANDLER aesl_fh;

		// "BUS_DST"
		char* tvin_BUS_DST = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_BUS_DST);
		char* tvout_BUS_DST = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_BUS_DST);

		// "matrix"
		char* tvin_matrix = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_matrix);

		// "Bound"
		char* tvin_Bound = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_Bound);

		CodeState = DUMP_INPUTS;
		static INTER_TCL_FILE tcl_file(INTER_TCL);
		int leading_zero;

		// [[transaction]]
		sprintf(tvin_BUS_DST, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_BUS_DST, tvin_BUS_DST);

		sc_bv<32>* BUS_DST_tvin_wrapc_buffer = new sc_bv<32>[64];

		// RTL Name: BUS_DST
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: matrix(31, 0)
				{
					// carray: (0) => (63) @ (1)
					for (int i_0 = 0; i_0 <= 63; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : matrix[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : matrix[0]
						// regulate_c_name       : matrix
						// input_type_conversion : matrix[i_0]
						if (&(matrix[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> matrix_tmp_mem;
							matrix_tmp_mem = matrix[i_0];
							BUS_DST_tvin_wrapc_buffer[hls_map_index].range(31, 0) = matrix_tmp_mem.range(31, 0);
                                 	       hls_map_index++;
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 64; i++)
		{
			sprintf(tvin_BUS_DST, "%s\n", (BUS_DST_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_BUS_DST, tvin_BUS_DST);
		}

		tcl_file.set_num(64, &tcl_file.BUS_DST_depth);
		sprintf(tvin_BUS_DST, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_BUS_DST, tvin_BUS_DST);

		// release memory allocation
		delete [] BUS_DST_tvin_wrapc_buffer;

		// [[transaction]]
		sprintf(tvin_matrix, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_matrix, tvin_matrix);

		sc_bv<32> matrix_tvin_wrapc_buffer;

		// RTL Name: matrix
		{
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_matrix, "%s\n", (matrix_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_matrix, tvin_matrix);
		}

		tcl_file.set_num(1, &tcl_file.matrix_depth);
		sprintf(tvin_matrix, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_matrix, tvin_matrix);

		// [[transaction]]
		sprintf(tvin_Bound, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_Bound, tvin_Bound);

		sc_bv<32> Bound_tvin_wrapc_buffer;

		// RTL Name: Bound
		{
			// bitslice(31, 0)
			{
				// celement: Bound(31, 0)
				{
					// carray: (0) => (0) @ (0)
					{
						// sub                   : 
						// ori_name              : Bound
						// sub_1st_elem          : 
						// ori_name_1st_elem     : Bound
						// regulate_c_name       : Bound
						// input_type_conversion : Bound
						if (&(Bound) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> Bound_tmp_mem;
							Bound_tmp_mem = Bound;
							Bound_tvin_wrapc_buffer.range(31, 0) = Bound_tmp_mem.range(31, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_Bound, "%s\n", (Bound_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_Bound, tvin_Bound);
		}

		tcl_file.set_num(1, &tcl_file.Bound_depth);
		sprintf(tvin_Bound, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_Bound, tvin_Bound);

// [call_c_dut] ---------->

		CodeState = CALL_C_DUT;
		BoundIDctMatrix(matrix, Bound);

		CodeState = DUMP_OUTPUTS;

		// [[transaction]]
		sprintf(tvout_BUS_DST, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_BUS_DST, tvout_BUS_DST);

		sc_bv<32>* BUS_DST_tvout_wrapc_buffer = new sc_bv<32>[64];

		// RTL Name: BUS_DST
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: matrix(31, 0)
				{
					// carray: (0) => (63) @ (1)
					for (int i_0 = 0; i_0 <= 63; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : matrix[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : matrix[0]
						// regulate_c_name       : matrix
						// input_type_conversion : matrix[i_0]
						if (&(matrix[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> matrix_tmp_mem;
							matrix_tmp_mem = matrix[i_0];
							BUS_DST_tvout_wrapc_buffer[hls_map_index].range(31, 0) = matrix_tmp_mem.range(31, 0);
                                 	       hls_map_index++;
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 64; i++)
		{
			sprintf(tvout_BUS_DST, "%s\n", (BUS_DST_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_BUS_DST, tvout_BUS_DST);
		}

		tcl_file.set_num(64, &tcl_file.BUS_DST_depth);
		sprintf(tvout_BUS_DST, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_BUS_DST, tvout_BUS_DST);

		// release memory allocation
		delete [] BUS_DST_tvout_wrapc_buffer;

		CodeState = DELETE_CHAR_BUFFERS;
		// release memory allocation: "BUS_DST"
		delete [] tvin_BUS_DST;
		delete [] tvout_BUS_DST;
		// release memory allocation: "matrix"
		delete [] tvin_matrix;
		// release memory allocation: "Bound"
		delete [] tvin_Bound;

		AESL_transaction++;

		tcl_file.set_num(AESL_transaction , &tcl_file.trans_num);
	}
}

