// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xboundidctmatrix.h"

extern XBoundidctmatrix_Config XBoundidctmatrix_ConfigTable[];

XBoundidctmatrix_Config *XBoundidctmatrix_LookupConfig(u16 DeviceId) {
	XBoundidctmatrix_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XBOUNDIDCTMATRIX_NUM_INSTANCES; Index++) {
		if (XBoundidctmatrix_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XBoundidctmatrix_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XBoundidctmatrix_Initialize(XBoundidctmatrix *InstancePtr, u16 DeviceId) {
	XBoundidctmatrix_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XBoundidctmatrix_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XBoundidctmatrix_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

