// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xchenidct.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XChenidct_CfgInitialize(XChenidct *InstancePtr, XChenidct_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Bus_ctrl_BaseAddress = ConfigPtr->Bus_ctrl_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XChenidct_Start(XChenidct *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XChenidct_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XCHENIDCT_BUS_CTRL_ADDR_AP_CTRL) & 0x80;
    XChenidct_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XCHENIDCT_BUS_CTRL_ADDR_AP_CTRL, Data | 0x01);
}

u32 XChenidct_IsDone(XChenidct *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XChenidct_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XCHENIDCT_BUS_CTRL_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XChenidct_IsIdle(XChenidct *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XChenidct_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XCHENIDCT_BUS_CTRL_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XChenidct_IsReady(XChenidct *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XChenidct_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XCHENIDCT_BUS_CTRL_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XChenidct_EnableAutoRestart(XChenidct *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XChenidct_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XCHENIDCT_BUS_CTRL_ADDR_AP_CTRL, 0x80);
}

void XChenidct_DisableAutoRestart(XChenidct *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XChenidct_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XCHENIDCT_BUS_CTRL_ADDR_AP_CTRL, 0);
}

void XChenidct_Set_x(XChenidct *InstancePtr, u64 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XChenidct_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XCHENIDCT_BUS_CTRL_ADDR_X_DATA, (u32)(Data));
    XChenidct_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XCHENIDCT_BUS_CTRL_ADDR_X_DATA + 4, (u32)(Data >> 32));
}

u64 XChenidct_Get_x(XChenidct *InstancePtr) {
    u64 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XChenidct_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XCHENIDCT_BUS_CTRL_ADDR_X_DATA);
    Data += (u64)XChenidct_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XCHENIDCT_BUS_CTRL_ADDR_X_DATA + 4) << 32;
    return Data;
}

void XChenidct_Set_y(XChenidct *InstancePtr, u64 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XChenidct_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XCHENIDCT_BUS_CTRL_ADDR_Y_DATA, (u32)(Data));
    XChenidct_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XCHENIDCT_BUS_CTRL_ADDR_Y_DATA + 4, (u32)(Data >> 32));
}

u64 XChenidct_Get_y(XChenidct *InstancePtr) {
    u64 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XChenidct_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XCHENIDCT_BUS_CTRL_ADDR_Y_DATA);
    Data += (u64)XChenidct_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XCHENIDCT_BUS_CTRL_ADDR_Y_DATA + 4) << 32;
    return Data;
}

void XChenidct_InterruptGlobalEnable(XChenidct *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XChenidct_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XCHENIDCT_BUS_CTRL_ADDR_GIE, 1);
}

void XChenidct_InterruptGlobalDisable(XChenidct *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XChenidct_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XCHENIDCT_BUS_CTRL_ADDR_GIE, 0);
}

void XChenidct_InterruptEnable(XChenidct *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XChenidct_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XCHENIDCT_BUS_CTRL_ADDR_IER);
    XChenidct_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XCHENIDCT_BUS_CTRL_ADDR_IER, Register | Mask);
}

void XChenidct_InterruptDisable(XChenidct *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XChenidct_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XCHENIDCT_BUS_CTRL_ADDR_IER);
    XChenidct_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XCHENIDCT_BUS_CTRL_ADDR_IER, Register & (~Mask));
}

void XChenidct_InterruptClear(XChenidct *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XChenidct_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XCHENIDCT_BUS_CTRL_ADDR_ISR, Mask);
}

u32 XChenidct_InterruptGetEnabled(XChenidct *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XChenidct_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XCHENIDCT_BUS_CTRL_ADDR_IER);
}

u32 XChenidct_InterruptGetStatus(XChenidct *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XChenidct_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XCHENIDCT_BUS_CTRL_ADDR_ISR);
}

